import { readFileSync } from "node:fs";

function equal<T>(actual: T, expected: T) {
  if (actual !== expected) {
    throw new Error(`Expected ${String(expected)}, got ${String(actual)}`);
  }
}

function countMatches(source: string, pattern: RegExp) {
  return Array.from(source.matchAll(pattern)).length;
}

function readSource(path: string) {
  return readFileSync(new URL(path, import.meta.url), "utf8").replace(/\r\n/g, "\n");
}

const appTsx = readSource("./App.tsx");
const tomlUtils = readSource("./tomlUtils.ts");
const appCss = readFileSync(new URL("./App.css", import.meta.url), "utf8").replace(/\r\n/g, "\n");
const gatewayProfile = readSource("./gatewayProfile.ts");
const configPreviews = readSource("./configPreviews.ts");
const vendorPresets = readSource("./vendorPresets.ts");
const uiTranslation = readSource("./i18n/uiTranslation.ts");
const gatewayPage = readSource("./components/GatewayPage.tsx");
const gatewayOverviewChart = readSource("./GatewayOverviewChart.tsx");
const gatewayHelpers = readSource("./components/gatewayHelpers.ts");
const gatewayProxyPanel = readSource("./components/GatewayProxyPanel.tsx");
const gatewaySnapshotUtils = readSource("./components/gatewaySnapshotUtils.ts");
const profilePresetUtils = readSource("./profilePresetUtils.ts");
const configJsonImport = readSource("./configJsonImport.ts");
const gatewayConfigOptions = readSource("./gatewayConfigOptions.ts");
const profileFormUtils = readSource("./profileFormUtils.ts");
const appSidebar = readSource("./features/app-shell/AppSidebar.tsx");
const claudeDesktopEffectiveConfigPanel = readSource("./features/config-options/ClaudeDesktopEffectiveConfigPanel.tsx");
const profileDisplayUtils = readSource("./profileDisplayUtils.ts");
const gatewayStore = readSource("./store/useGatewayStore.ts");
const appUiStore = readSource("./store/useAppUiStore.ts");
const appConstants = readSource("./appConstants.ts");
const nativeApi = readSource("./nativeApi.ts");
const appTypes = readSource("./appTypes.ts");

equal(gatewayProfile.includes("function gatewayProfileUsesProxy"), true);
equal(configPreviews.includes("function gatewayClientAuthEnv"), true);
equal(configPreviews.includes("...gatewayClientAuthEnv(form, target)"), true);
equal(appConstants.includes("export const CODEX_LOCAL_PROXY_BASE_URL"), true);
equal(appConstants.includes("CLAUDE_CLI_LOCAL_GATEWAY_AUTH_TOKEN = \"agent-switch-local-gateway\""), true);
equal(configPreviews.includes("return { ANTHROPIC_AUTH_TOKEN: CLAUDE_CLI_LOCAL_GATEWAY_AUTH_TOKEN };"), true);
equal(gatewayProfile.includes("function isOfficialAnthropicBaseUrl"), true);
equal(gatewayProfile.includes('profile.compat_mode ?? (isOfficialAnthropicBaseUrl(profile.base_url) ? "direct" : "proxy")'), true);
equal(profileFormUtils.includes("function normalizeGatewayProfileForApply"), true);
equal(profileFormUtils.includes("function gatewayFormCompatMode"), true);
equal(profileFormUtils.includes("function gatewayPresetUpstreamBaseUrl"), true);
equal(profileFormUtils.includes("function presetManagedGatewayBaseUrl"), true);
equal(profileFormUtils.includes("const usesPresetDefaultUrl = profileBaseUrl === presetBaseUrl || profileBaseUrl === presetRequestUrl;"), true);
equal(profileFormUtils.includes("return gatewayPresetUpstreamBaseUrl(preset, targetKey);"), true);
equal(profileFormUtils.includes("function gatewayFormApiFormat"), true);
equal(profileFormUtils.includes("function gatewayFormAuthField"), true);
equal(profileFormUtils.includes("function gatewayFormAuthFieldForTarget"), true);
equal(profileFormUtils.includes("const compatMode = gatewayFormCompatMode(profile, preset);"), true);
equal(profileFormUtils.includes("gatewayFormApiFormat(profile.api_format, compatMode, preset, target)"), true);
equal(profileFormUtils.includes("gatewayFormAuthFieldForTarget(profile.auth_field, preset, targetKey)"), true);
equal(appTsx.includes("const canEditGatewayProtocolFields = selectedPreset === \"custom\";"), true);
equal(profileFormUtils.includes("function customApiFormatsForTarget"), true);
equal(profileFormUtils.includes("function authFieldsForCustomTarget"), true);
equal(profileFormUtils.includes("function defaultAuthFieldForApiFormat"), true);
equal(appTsx.includes("customApiFormatsForTarget(target).includes(value as ApiFormat)"), true);
equal(appTsx.includes("authFieldsForCustomTarget(target, addForm.api_format).includes(value as AuthField)"), true);
equal(appTsx.includes("上游 API 格式"), true);
equal(appTsx.includes("上游认证方式"), true);
equal(appTsx.includes("按模型厂商与目标 agent 官方文档选择"), true);
equal(appTsx.includes("用于 Switch++ 连接上游和模型发现；目标 agent 的配置文件会按自身格式写入。"), true);
equal(appTsx.includes("获取 API Key"), false);
equal(appTsx.includes(".api_key_url"), false);
equal(appTsx.includes("handleDiscoverProviderModels"), true);
equal(appTsx.includes("providerModelCandidates"), true);
equal(appTsx.includes("renderModelDiscoveryField"), true);
const modelDiscoveryField = readSource("./components/ModelDiscoveryField.tsx");
equal(modelDiscoveryField.includes("所有新增页都使用同一套模型发现；若厂商不开放模型端点，可直接填写模型 ID。"), true);
equal(modelDiscoveryField.includes("onAddExtraModel"), true);
equal(modelDiscoveryField.includes("aria-label=\"添加自定义模型\""), true);
equal(modelDiscoveryField.includes("extraModels.map"), true);
equal(modelDiscoveryField.includes("activeModelInputIndex"), true);
equal(modelDiscoveryField.includes("onChangeModelAt(activeModelInputIndex, model)"), true);
equal(modelDiscoveryField.includes("ccr-model-grid"), true);
equal(modelDiscoveryField.includes("DndContext"), true);
equal(modelDiscoveryField.includes("SortableContext"), true);
equal(modelDiscoveryField.includes("SortableProfileCard"), true);
equal(modelDiscoveryField.includes("ccr-config-drag-handle"), false);
equal(modelDiscoveryField.includes("function createModelRowId"), true);
equal(modelDiscoveryField.includes("const [modelItemIds, setModelItemIds] = useState"), true);
equal(modelDiscoveryField.includes("modelValues.map((_, index) => `model-${index}`)"), false);
equal(modelDiscoveryField.includes("setModelItemIds((ids) => reorderModelRowIds(ids, fromIndex, toIndex))"), true);
equal(modelDiscoveryField.includes("draggable={canDragModelItem}"), false);
equal(modelDiscoveryField.includes("onDragStart"), false);
equal(modelDiscoveryField.includes("onReorderModels"), true);
equal(appCss.includes(".ccr-model-grid {\n  display: grid;\n  grid-template-columns: 1fr;"), true);
equal(appCss.includes(".ccr-model-grid {\n  display: grid;\n  grid-template-columns: repeat(2, minmax(0, 1fr));"), false);
equal(appCss.includes(".ccr-model-list-item .ccr-config-drag-handle"), true);
equal(appCss.includes(".ccr-model-drag-handle"), false);
equal(appTsx.includes("codexExtraModels"), true);
equal(appTsx.includes("function reorderCodexModel"), true);
equal(appTsx.includes("uniqueModelNames([resolvedModel, ...codexExtraModels])"), true);
equal(appTsx.includes("models_user_defined: codexFormForSubmit.connection_mode !== \"official\""), true);
equal(appTsx.includes("buildCodexModelCatalogPreview(codexFormForSubmit, codexProfileModels.slice(1))"), true);
equal(profilePresetUtils.includes("function codexPresetSupportsCodex"), true);
equal(profilePresetUtils.includes("function codexPresetDisabledReason"), true);
equal(profilePresetUtils.includes("preset.codex_support_status === \"responses\""), true);
equal(profilePresetUtils.includes("preset.codex_support_status === \"gateway\""), true);
equal(appTsx.includes("currentSelectedPreset?.codex_support_note"), true);
equal(appTsx.includes("官网依据"), true);
equal(profilePresetUtils.includes("该厂商未确认支持 Codex 厂商连接或 Switch++ 本地兼容网关，暂不建议添加。"), true);
equal(appTsx.includes("aria-disabled={isDisabled}"), true);
equal(appTsx.includes("<Tooltip.Trigger>{presetCard}</Tooltip.Trigger>"), true);
equal(appTsx.includes("<Tooltip.Trigger>{modeButton}</Tooltip.Trigger>"), true);
equal(appCss.includes(".ccr-address-switch-btn.disabled"), true);
equal(appTsx.includes("厂商预设已内置协议与认证方式"), true);
equal(appTsx.includes("Claude Code 仍按 Anthropic Messages 请求本地网关"), true);
equal(appTsx.includes("为兼容截图/图片上传，Switch++ 可能会把上游协议自动设为 OpenAI Chat Completions"), false);
equal(gatewayProfile.includes("function isAsciiHeaderValue"), true);
equal(appTsx.includes("API Key 只能包含 ASCII 字符"), true);
equal(profileFormUtils.includes("const compatMode = next.compat_mode ?? claudeCompatModeForPreset(preset);"), true);
equal(profileFormUtils.includes("next.api_format = gatewayFormApiFormat(profile.api_format, compatMode, preset, target);"), true);
equal(profileFormUtils.includes("next.base_url = gatewayPresetUpstreamBaseUrl(preset, target);"), true);
equal(profileFormUtils.includes("base_url: presetManagedGatewayBaseUrl(profile, preset, targetKey),"), true);
equal(profileFormUtils.includes("next.upstream_model = resolveGatewayUpstreamModel(profile, preset)"), true);
equal(profileFormUtils.includes("next.auth_field = vendorPresetAuthFieldForTarget(preset, target);"), true);
equal(vendorPresets.includes("id: \"minimax-coding-cn\""), true);
equal(vendorPresets.includes("auth_field: \"ANTHROPIC_API_KEY\""), true);
equal(vendorPresets.includes("codex_support_status: \"responses\""), true);
equal(vendorPresets.includes("codex_support_status: \"gateway\""), true);
equal(vendorPresets.includes("DeepSeek 官方文档提供 Chat Completions 端点；Codex 通过 Switch++ 本地网关适配后可用。"), true);
equal(vendorPresets.includes("https://developers.openai.com/codex/config-reference/"), true);
equal(vendorPresets.includes("https://help.aliyun.com/zh/model-studio/codex"), true);
equal(vendorPresets.includes("https://openrouter.ai/docs/api/api-reference/responses/create-responses"), true);
equal(appTsx.includes("const appliedGatewayProfile = useMemo"), false);
equal(appTsx.includes("import { isProxyTarget, type ProxyTargetKey } from \"./proxyTargets.ts\";"), true);
equal(appTsx.includes("import { targetOptions, visibleTargetOptions } from \"./targetOptions.ts\";"), true);
equal(gatewayHelpers.includes("function codexProfileUsesProxy"), true);
equal(gatewayHelpers.includes("function codexProfileUsesLocalGateway"), true);
equal(gatewaySnapshotUtils.includes("hasProxy: codexProfileUsesLocalGateway(profile)"), true);
equal(appTsx.includes("const activeProxyProfile = isProxyTarget(target)"), false);
equal(appTsx.includes("function renderGatewayProxyPanel"), false);
equal(appTsx.includes("if (!snapshot || (!snapshot.hasProfile && !isCodexTarget(snapshot.targetKey))) return null;"), false);
equal(appTsx.includes("{renderGatewayProxyPanel()}"), false);
equal(appTsx.includes("function toggleProfileGateway"), false);
equal(appTsx.includes("ccr-config-gateway-toggle"), false);
equal(appTsx.includes("ccr-config-gateway-advice"), false);
equal(appTsx.includes("const profileGatewayToggleDisabled = busy || codexProxyBusy || !isApplied;"), false);
equal(appTsx.includes("profileGatewayRequirement && (!(\"connection_mode\" in profile) || profile.connection_mode !== \"official\")"), false);
equal(appTsx.includes("profileGatewayRequirement && profileGatewayRequirement.level !== \"none\""), false);
equal(appTsx.includes("const savedProfileCompatLabel = profileCompatModeMeta(profile, target);"), false);
equal(appTsx.includes("const profileStatusLabel = profileRouteStatusLabel(profile);"), true);
equal(appTsx.includes("<span className=\"ccr-config-meta-text\">{profileStatusLabel}</span>"), true);
equal(appTsx.includes("disabled={profileGatewayToggleDisabled}"), false);
equal(/<span className="ccr-config-gateway-advice">[\s\S]*ccr-config-gateway-toggle/.test(appTsx), false);
equal(/ccr-config-gateway-toggle[\s\S]*\/>\s*\) : null\}\s*\{renderGatewayRequirementIcon\(profileGatewayRequirement\)\}/.test(appTsx), false);
equal(appTsx.includes(">网关</Switch>"), false);
equal(/<div className="ccr-config-actions">\s*\{showProfileGatewayToggle \?/.test(appTsx), false);
equal(gatewayProxyPanel.includes("const profileLabel = snapshot.profile?.display_name || \"未选择配置\";"), true);
equal(gatewayProxyPanel.includes("const isOfficialCodex = isCodexProfile(snapshot.profile) && snapshot.profile.connection_mode === \"official\";"), false);
equal(gatewayProxyPanel.includes("const startLabel = isOfficialCodex ? \"观测\" : \"开启\";"), false);
equal(gatewayProxyPanel.includes("\"未配置本地网关\""), false);
equal(configPreviews.includes("CLAUDE_CLI_LOCAL_PROXY_BASE_URL"), true);
equal(configPreviews.includes("CLAUDE_DESKTOP_LOCAL_PROXY_BASE_URL"), true);
equal(configPreviews.includes("localClaudeProxyBaseUrlForTarget"), true);
equal(gatewayConfigOptions.includes("skip_introduction"), false);
equal(configPreviews.includes("skipIntroduction"), false);
equal(configPreviews.includes("function minimaxMcpServerConfig"), true);
equal(configPreviews.includes("settings.mcpServers = { MiniMax: minimaxMcpServer };"), true);
equal(configPreviews.includes("\"minimax-coding-plan-mcp\""), true);
equal(configPreviews.includes("MINIMAX_API_HOST"), true);
const gatewayConfigOptionsPanel = readSource("./components/GatewayConfigOptionsPanel.tsx");
equal(gatewayConfigOptionsPanel.includes("recommendedClaudeGatewayConfigOptionKeys"), true);
equal(appTsx.includes("withRecommendedGatewayConfigOptions"), true);
equal(appTsx.includes("function resetCodexOptionsToDefault()"), false);
equal(appTsx.includes("function resetGatewayTargetOptionsToDefault()"), false);
equal(appTsx.includes("function resetClaudeOptionsToDefault()"), false);
equal(appTsx.includes("恢复默认"), false);
equal(appTsx.includes("ccr-option-action secondary"), false);
equal(gatewayConfigOptionsPanel.includes("恢复默认"), false);
equal(gatewayConfigOptionsPanel.includes("ccr-option-action secondary"), false);
equal(gatewayConfigOptions.includes("  \"auto_compact\",\n  \"compact_early\","), true);
equal(gatewayConfigOptions.includes("  \"hide_ai_signature\","), true);
equal(gatewayConfigOptions.includes("  \"disable_telemetry\","), true);
equal(gatewayConfigOptions.includes("  \"disable_nonessential_traffic\","), true);
equal(gatewayConfigOptionsPanel.includes("推荐默认开启"), true);
equal(gatewayConfigOptionsPanel.includes("recommendedClaudeDesktopConfigOptionKeys"), true);
equal(appTsx.includes("renderClaudeConfigOptions"), true);
equal(appTsx.includes("renderClaudeDesktopEffectiveConfig"), false);
equal(claudeDesktopEffectiveConfigPanel.includes("Desktop 实际生效配置"), true);
equal(appUiStore.includes("desktopEffectiveConfigOpen: false"), true);
equal(claudeDesktopEffectiveConfigPanel.includes("aria-expanded={open}"), true);
equal(claudeDesktopEffectiveConfigPanel.includes("{open ? ("), true);
equal(appTsx.includes("provider_model_map"), true);
equal(appTsx.includes("providerModelMapFallback"), true);
equal(profileFormUtils.includes("function providerModelPlaceholder"), true);
equal(profileFormUtils.includes("!isModelMapEmpty(form.provider_model_map)"), true);
equal(appTsx.includes("validateProviderModelMap("), true);
equal(appTsx.includes("target === \"claude_desktop\" && form.compat_mode === \"proxy\""), true);
equal(appTsx.includes("placeholder={providerModelPlaceholder(key, addForm, currentSelectedPreset)}"), true);
equal(appTsx.includes("placeholder=\"qwen3.6-plus / deepseek-v4-pro\""), false);
equal(appTsx.includes("<label>上游真实模型</label>"), false);
equal(appTsx.includes(": (formForSubmit.model || formForSubmit.model_map.main);"), false);
equal(appTsx.includes(": formForSubmit.model_map.main;"), true);
equal(appTsx.includes("左侧是 Claude Desktop profile 的模型别名；右侧填写这类请求要转发到的厂商真实模型。"), true);
equal(profileDisplayUtils.includes("return profile.upstream_model || profile.provider_model_map?.main || profile.model_map.main"), true);
equal(appTsx.includes("<label>对应上游模型</label>"), true);
equal(appTsx.includes("{label}（上游）"), false);
equal(appTsx.includes("ArrowRight as ArrowRightIcon"), true);
equal(appTsx.includes("<ArrowRightIcon className=\"ccr-model-map-arrow-icon\" weight=\"bold\" />"), true);
equal(appTsx.includes("[\"main\", \"主模型\"],\n                      [\"opus\", \"Opus 默认模型\"],\n                      [\"sonnet\", \"Sonnet 默认模型\"],\n                      [\"haiku\", \"Haiku 默认模型\"]"), true);
equal(countMatches(appTsx, /\["main", "主模型"\],\s*\["opus", "Opus 默认模型"\],\s*\["sonnet", "Sonnet 默认模型"\],\s*\["haiku", "Haiku 默认模型"\]/g), 3);
equal(countMatches(appTsx, /\["main", "主模型"\],\s*\["haiku", "Haiku 默认模型"\],\s*\["sonnet", "Sonnet 默认模型"\],\s*\["opus", "Opus 默认模型"\]/g), 0);
equal(configPreviews.includes("function claudeCodeModelEnvValue"), true);
equal(/ANTHROPIC_MODEL: modelMap\.main,\s*ANTHROPIC_DEFAULT_OPUS_MODEL: modelMap\.opus,\s*ANTHROPIC_DEFAULT_SONNET_MODEL: modelMap\.sonnet,\s*ANTHROPIC_DEFAULT_HAIKU_MODEL: modelMap\.haiku,/.test(configPreviews), true);
equal(/ANTHROPIC_MODEL: modelMap\.main,\s*ANTHROPIC_DEFAULT_HAIKU_MODEL: modelMap\.haiku,\s*ANTHROPIC_DEFAULT_SONNET_MODEL: modelMap\.sonnet,\s*ANTHROPIC_DEFAULT_OPUS_MODEL: modelMap\.opus,/.test(configPreviews), false);
equal(configJsonImport.includes("\"ANTHROPIC_MODEL\",\n    \"ANTHROPIC_DEFAULT_OPUS_MODEL\",\n    \"ANTHROPIC_DEFAULT_SONNET_MODEL\",\n    \"ANTHROPIC_DEFAULT_HAIKU_MODEL\","), true);
equal(configJsonImport.includes("\"ANTHROPIC_MODEL\",\n    \"ANTHROPIC_DEFAULT_HAIKU_MODEL\",\n    \"ANTHROPIC_DEFAULT_SONNET_MODEL\",\n    \"ANTHROPIC_DEFAULT_OPUS_MODEL\","), false);
equal(appTsx.includes("ccr-model-map-arrow"), true);
equal(appCss.includes(".ccr-model-map-row"), true);
equal(appCss.includes(".ccr-model-alias-row"), false);
equal(appTsx.includes("renderClaudeConfigOptions(\"Claude Desktop 选项\")"), false);
equal(appTsx.includes("Claude Desktop 选项"), true);
equal(appTsx.includes("target === \"claude_desktop\""), true);
equal(/<ClaudeDesktopEffectiveConfigPanel[\s\S]*\{renderClaudeConfigOptions\(targetConfigOptionsLabel\)\}[\s\S]*Claude Desktop 实际写入文件/.test(appTsx), true);
equal(gatewayConfigOptions.includes("recommendedClaudeDesktopConfigOptionKeys"), true);
equal(gatewayConfigOptions.includes("\"disable_telemetry\""), true);
equal(gatewayConfigOptions.includes("\"disable_nonessential_traffic\""), true);
equal(gatewayConfigOptionsPanel.includes("configFields"), true);
equal(gatewayConfigOptionsPanel.includes("写入字段"), true);
equal(appTsx.includes("readClaudeCodeSettings"), true);
equal(appTsx.includes("function handleSyncClaudeCodeSettings"), true);
equal(appTsx.includes("已同步本地 Claude Code 配置。"), true);
equal(appTsx.includes("readClaudeDesktopConfigFiles"), true);
equal(configPreviews.includes("function buildClaudeDesktopProfileConfigPreview"), true);
equal(configPreviews.includes("agentSwitchUpstreamModel"), true);
equal(configPreviews.includes("agentSwitchProviderModelMap"), true);
equal(configPreviews.includes("function buildClaudeDesktopMetaConfigPreview"), true);
equal(appTsx.includes("function handleSyncClaudeDesktopConfigFiles"), true);
equal(appTsx.includes("Claude Desktop 实际写入文件"), true);
equal(appTsx.includes("_meta.json"), true);
equal(gatewayPage.includes("codexProxyStatus?.claude_desktop"), true);
equal(gatewayPage.includes("codexProxyStatus?.claude_cli"), true);
equal(gatewaySnapshotUtils.includes("if (profile && !hasProxy && targetKey !== \"claude_cli\" && !canStart) return null;"), true);
equal(gatewaySnapshotUtils.includes("const running = Boolean(codexProxyStatus?.running && targetProxyStatus);"), true);
equal(gatewaySnapshotUtils.includes("const baseUrl = isCodexTarget(targetKey)"), true);
equal(gatewayPage.includes("当前走厂商连接"), true);
equal(gatewayPage.includes("isCodexDirectProfile(snapshot.profile)"), true);
equal(appTsx.includes("`${targetDisplayName(proxyTarget)} 已切换为本地兼容网关。`"), false);
equal(appTsx.includes("`${targetDisplayName(proxyTarget)} 已切换为直连，兼容网关已关闭。`"), false);
equal((appTsx.match(/proxyTarget === "codex" \|\| proxyTarget === "claude_cli"/g) ?? []).length, 0);
equal(countMatches(appTsx, /const refreshed = await nativeApi\.loadAppState\(\);/g), 0);
equal(gatewayPage.includes("onStartProxy(snapshot.targetKey)"), false);
equal(gatewayPage.includes("onStopProxy(snapshot.targetKey)"), false);
equal(appTsx.includes("function refreshClaudeCliEditFormFromState"), true);
equal(appTsx.includes("refreshClaudeCliEditFormFromState(refreshed);"), true);
equal(gatewayStore.includes("codexProxyDetailTab: \"overview\""), true);
equal(gatewayStore.includes("codexProxyOverviewError: \"\""), true);
equal(appTsx.includes("setCodexProxyOverviewError(`统计图表加载失败：${String(error)}`);"), true);
equal(appTsx.includes("统计图表加载失败"), true);
equal(appTsx.includes("重试"), true);
equal(appTsx.includes("codex-proxy-call-recorded"), true);
equal(appTsx.includes("window.setInterval(refreshProxyStatus, 15000)"), true);
equal(appTsx.includes("view !== \"gateway\""), true);
equal(appTsx.includes(".codexProxyCallsPage(selectedTarget, codexProxyCallPage, codexProxyCallPageSize, codexProxyOverviewRange, codexProxyOverviewBucket)"), true);
equal(appTsx.includes("setView(\"gateway\")"), true);
equal(gatewayPage.includes("function GatewayPage"), true);
equal(gatewayPage.includes("const gatewayItems = gatewayProxyTargetOptions.map((option) => ({"), true);
equal(gatewayPage.includes("ccr-proxy-action-switch"), false);
equal(appTsx.includes("handleGatewayStartProxy"), false);
equal(appTsx.includes("handleGatewayStopProxy"), false);
equal(appTsx.includes("async function startCodexProxy"), false);
equal(appTsx.includes("async function stopCodexProxy"), false);
equal(gatewayProxyPanel.includes("aria-label=\"查看兼容网关详情\""), true);
equal(gatewayProxyPanel.includes("ccr-proxy-action-btn"), false);
equal(gatewayProxyPanel.includes("onStartProxy"), false);
equal(gatewayProxyPanel.includes("onStopProxy"), false);
equal(appSidebar.includes("兼容网关</span>"), true);
equal(gatewayPage.includes("className=\"ccr-proxy-call-model\""), true);
equal(gatewayPage.includes("title={call.model}"), true);
equal(appCss.includes(".ccr-codex-proxy-model"), true);
equal(appTsx.includes("ccr-gateway-app-tabs"), true);
equal(gatewayPage.includes("role=\"tablist\" aria-label=\"兼容网关应用列表\""), true);
equal(gatewayPage.includes("aria-label={`${option.title}：${statusLabel}`}"), true);
equal(appTsx.includes("<strong>{option.title}</strong>"), false);
equal(gatewayPage.includes("className={statusClassName} aria-hidden=\"true\""), true);
equal(appCss.includes("width: 38px;\n  height: 38px;"), true);
equal(appCss.includes(".ccr-gateway-app-tab-status.running::after"), true);
equal(appTsx.includes("setGatewayPageTarget(null)"), true);
equal(gatewaySnapshotUtils.includes("if (!profile && !isCodexTarget(targetKey)) return null;"), true);
const gatewayRequirementIcon = readSource("./components/GatewayRequirementIcon.tsx");
equal(appTsx.includes("function renderGatewayRequirementIcon"), false);
equal(gatewayRequirementIcon.includes("<Tooltip.Root delay={350}>"), true);
equal(gatewayRequirementIcon.includes("ccr-gateway-requirement-badge"), true);
equal(gatewayRequirementIcon.includes("<div className=\"ccr-tooltip-label\">网关状态</div>"), true);
equal(gatewayRequirementIcon.includes("<div className=\"ccr-tooltip-label\">说明</div>"), true);
equal(gatewayRequirementIcon.includes("<div className=\"ccr-tooltip-label\">收益</div>"), true);
equal(gatewayRequirementIcon.includes("<div className=\"ccr-tooltip-label\">仍有限制</div>"), true);
equal(uiTranslation.includes('"网关状态": "Gateway Status"'), true);
equal(uiTranslation.includes('"收益": "Benefit"'), true);
equal(uiTranslation.includes('"仍有限制": "Remaining Limits"'), true);
equal(gatewayRequirementIcon.includes("requirementTooltipText"), true);
equal(gatewayRequirementIcon.includes("splitGatewayRequirementDetail"), true);
equal(appCss.includes(".ccr-gateway-requirement-badge"), true);
equal(appCss.includes(".ccr-gateway-requirement-tooltip"), true);
equal(appCss.includes(".ccr-config-gateway-advice"), true);
equal(appCss.includes(".switch input:disabled + .switch-control"), true);
equal(appCss.includes(".ccr-config-gateway-toggle:has(input:disabled)"), true);
equal(gatewayPage.includes("基本信息"), true);
equal(gatewayPage.includes("概览"), true);
equal(gatewaySnapshotUtils.includes("export function gatewayScopeLabel"), true);
equal(gatewayPage.includes("Chat / Responses / Models"), true);
equal(gatewayPage.includes("Anthropic Messages / Models"), true);
equal(gatewayPage.includes("<span className=\"ccr-proxy-meta-label\">范围</span>"), true);
equal(gatewayPage.includes("<span className=\"ccr-proxy-meta-label\">入口</span>"), true);
equal(gatewayPage.includes("<span className=\"ccr-proxy-meta-label\">处理方式</span>"), true);
equal(gatewayPage.includes("<span className=\"ccr-proxy-meta-label\">认证</span>"), true);
equal(gatewayPage.includes("<span className=\"ccr-proxy-meta-label\">输入支持</span>"), true);
equal(gatewayPage.includes("图片映射取决于上游；文件输入不支持"), true);
equal(gatewayPage.includes("请求、Token、Cache、错误详情"), true);
equal(gatewayPage.includes("详细信息"), true);
equal(gatewayPage.includes("onDetailTabChange(tab)"), true);
equal(gatewayStore.includes("codexProxyCallPage: 1"), true);
equal(gatewayStore.includes("codexProxyCallsPage: null"), true);
equal(gatewayStore.includes("codexProxyCallDetails: {}"), true);
equal(gatewayPage.includes("const translatedCallError = call.error ? translateUiText(call.error, language) : \"\";"), true);
equal(uiTranslation.includes("[/^上游 (.+) 请求失败：(.+)$/s, \"Upstream $1 request failed: $2\"]"), true);
equal(gatewayPage.includes("className={call.error ? \"ccr-proxy-call-row error\" : \"ccr-proxy-call-row\"}"), true);
equal(gatewayPage.includes("event.stopPropagation();"), true);
equal(appTsx.includes(".codexProxyCallsPage"), true);
equal(appTsx.includes(".codexProxyCallDetail"), true);
equal(gatewayPage.includes("const PROXY_CALL_PAGE_SIZE_OPTIONS = [20, 50, 100] as const;"), true);
equal(gatewayStore.includes("codexProxyCallPageSize: 50"), true);
equal(gatewayPage.includes("&& codexProxyCallsPage.page_size === codexProxyCallPageSize"), true);
equal(gatewayPage.includes("const proxyCallTotal = callsPage?.total ?? Number(overviewStats?.request_count ?? 0);"), true);
equal(gatewayPage.includes("总条目数：{formatProxyNumber(snapshot.proxyCallTotal)}"), true);
equal(appTsx.includes("最多 100 页"), false);
equal(appTsx.includes(">清空记录<"), false);
equal(appCss.includes(".ccr-gateway-card.realtime .ccr-proxy-call-table-wrap {\n  flex: none;\n  min-height: 0;\n  max-height: none;\n  overflow-x: auto;\n  overflow-y: visible;"), true);
equal(appCss.includes("max-height: 420px;"), false);
equal(gatewayPage.includes("调用记录"), true);
equal(appTsx.includes("Input"), true);
equal(appTsx.includes("Output"), true);
equal(gatewayPage.includes("输入/输出 Token"), true);
equal(uiTranslation.includes("\"输入 Token\": \"Input Tokens\""), true);
equal(uiTranslation.includes("\"输出 Token\": \"Output Tokens\""), true);
equal(gatewayPage.includes("缓存命中"), true);
equal(gatewayOverviewChart.includes("stats.cache_tokens"), true);
equal(gatewayOverviewChart.includes("stats.latest_cache_tokens"), true);
equal(gatewayOverviewChart.includes('overview.target === "claude_desktop"'), true);
equal(gatewayOverviewChart.includes("缓存命中"), true);
equal(gatewayProxyPanel.includes("function formatProxyTokenMillions"), true);
equal(gatewayProxyPanel.includes("function formatProxyTokenK"), true);
equal(gatewayProxyPanel.includes("function formatProxyTokenTooltip"), true);
equal(gatewayProxyPanel.includes("return `${formatProxyNumber(value)} tokens`;"), true);
equal(gatewayProxyPanel.includes("const millions = tokens / 1_000_000;"), true);
equal(gatewayPage.includes("{formatProxyTokenK(snapshot.stats.input_tokens)}/{formatProxyTokenK(snapshot.stats.output_tokens)}"), true);
equal(gatewayPage.includes('className="ccr-proxy-meta-item" title="当前网关范围累计记录的请求数量"'), true);
equal(gatewayPage.includes('className="ccr-proxy-meta-item" title={`输入 ${formatProxyTokenTooltip(snapshot.stats.input_tokens)} / 输出 ${formatProxyTokenTooltip(snapshot.stats.output_tokens)}`}'), true);
equal(gatewayPage.includes("{formatProxyTokenK(snapshot.stats.total_tokens)}"), true);
equal(gatewayPage.includes('className="ccr-proxy-meta-item" title={formatProxyTokenTooltip(snapshot.stats.total_tokens)}'), true);
equal(gatewayPage.includes("{formatProxyTokenK(snapshot.stats.cache_tokens)}"), true);
equal(gatewayPage.includes("formatProxyTokenK(snapshot.stats.cache_creation_tokens)"), true);
equal(gatewayPage.includes("title={`命中 ${formatProxyTokenTooltip(snapshot.stats.cache_tokens)} / 写入 ${formatProxyTokenTooltip(snapshot.stats.cache_creation_tokens)}`}"), true);
equal(gatewayPage.includes("const proxyCallPageErrorCount = overviewStats?.error_count"), true);
equal(gatewayPage.includes("proxyCallPageErrorCount,"), true);
equal(gatewayPage.includes("<span className=\"ccr-proxy-meta-label\">错误数</span>"), true);
equal(gatewayPage.includes('className="ccr-proxy-meta-item" title="当前统计范围内 error 非空或 HTTP 状态码大于等于 400 的数量"'), true);
equal(gatewayPage.includes("当前统计范围内 error 非空或 HTTP 状态码大于等于 400 的数量"), true);
equal(appCss.includes(".ccr-codex-proxy-meta.compact-grid {\n  grid-template-columns: repeat(5, minmax(0, 1fr));"), true);
equal(gatewayPage.includes("Tokens"), true);
equal(gatewayPage.includes("Cache"), true);
equal(uiTranslation.includes("\"清空记录\": \"Clear records\""), true);
equal(gatewayPage.includes("call.cache_tokens"), true);
equal(gatewayPage.includes("call.cache_creation_tokens"), true);
equal(gatewayPage.includes("function formatProxyCallCacheState"), true);
equal(gatewayPage.includes("label: \"写入\""), true);
equal(gatewayPage.includes("label: \"未报告\""), true);
equal(gatewayPage.includes("label: \"无缓存\""), true);
equal(gatewayPage.includes("snapshot.stats.cache_tokens"), true);
equal(gatewayPage.includes("snapshot.stats.cache_creation_tokens"), true);
equal(gatewayPage.includes("call.input_tokens"), true);
equal(gatewayPage.includes("call.output_tokens"), true);
equal(gatewayPage.includes("call.total_tokens"), true);
equal(appTypes.includes("cache_creation_tokens: number"), true);
equal(appTypes.includes("cache_reported: boolean"), true);
equal(gatewayPage.includes("detail?.input"), true);
equal(gatewayPage.includes("detail?.output"), true);
equal(appTsx.includes("shouldReapplyEditedProfile"), true);
equal(gatewayHelpers.includes("function targetDisplayName"), true);
equal(gatewayPage.includes("const gatewayClientName = targetDisplayName(snapshot.targetKey);"), true);
equal(gatewayPage.includes("`${gatewayClientName} 正在请求本地兼容网关。`"), true);
equal(gatewayPage.includes("`${gatewayClientName} 当前不会请求本地兼容网关。`"), true);
equal(gatewayConfigOptions.includes("bypass_permissions"), true);
equal(gatewayConfigOptions.includes("Bypass permissions"), true);
equal(gatewayConfigOptions.includes("permissions.defaultMode"), true);
equal(gatewayHelpers.includes("function applyRestartMessage"), true);
equal(appTsx.includes("配置已写入，重启 ${targetDisplayName(applyTarget)} 后生效。"), true);
equal(appTsx.includes("配置已保存，重启 ${targetDisplayName(target)} 后生效。"), true);
equal(appTsx.includes("配置已保存。未应用到客户端。"), true);
equal(gatewayHelpers.includes("已请求退出"), true);
equal(appTsx.includes("读取兼容网关状态失败"), true);
equal(appTsx.includes("已接管本地兼容网关，可统计请求。"), true);
equal(appTsx.includes("已同步本地 Claude Code 配置。"), true);
equal(appTsx.includes("function applyProfileToClientWithoutExit"), true);
equal(/await applyProfileToClientWithoutExit\(\s*target,\s*editingProfile!\.id,\s*nextState,/.test(appTsx), true);
equal(/await applyProfileToClientWithoutExit\(\s*target,\s*submittedProfileId,\s*nextState,/.test(appTsx), true);
equal(appTsx.includes("await quitTargetAppAfterApply(target, `${targetDisplayName(target)} 配置已保存并写入客户端`);"), false);
equal(uiTranslation.includes('[/^(.+) 配置已写入，重启 (.+) 后生效。$/, "$1 config written. Restart $2 for it to take effect."]'), true);
equal(appTsx.includes("const targetAdvancedProtocolNote ="), true);
equal(appTsx.includes("const targetBaseUrlLabel ="), true);
equal(appTsx.includes("const targetBaseUrlHelp ="), true);
equal(appTsx.includes('addForm.compat_mode === "proxy"'), true);
equal(appTsx.includes("Anthropic 上游地址"), true);
equal(appTsx.includes("Claude Desktop 上游地址"), true);
equal(appTsx.includes("该地址保存为厂商上游地址；Claude Desktop 实际读取本地桌面网关，并由 Switch++ 按下方模型映射转发。"), true);
equal(claudeDesktopEffectiveConfigPanel.includes("agentSwitchRoute"), true);
equal(claudeDesktopEffectiveConfigPanel.includes("agentSwitchUpstreamBaseUrl"), true);
equal(appTsx.includes("Claude Code 可直接使用 Anthropic 兼容地址；开启本地网关后可获得记录、预检和统一启停。"), true);
equal(appTsx.includes("使用本机 Codex 官方登录，无需填写 API Key 或 Base URL；没有官方账号时可直接使用三方配置。"), true);
equal(appTsx.includes("模型是否可用，以当前 ChatGPT 套餐、额度和 Codex 模型菜单为准。"), true);
equal(appTsx.includes("需要刷新 auth.json 或 config.toml 时，请在下方“官方登录配置”中同步。"), true);
equal(appTsx.includes("gpt-5.2"), false);
equal(appTsx.includes("同步官方配置失败：${String(error)}。没有官方账号不影响三方配置使用。"), true);
equal(appTsx.includes("function renderOfficialCodexModelField()"), true);
equal(appTsx.includes("import { mergeCodexOfficialModelIntoToml } from \"./tomlUtils.ts\";"), true);
equal(tomlUtils.includes("function mergeCodexOfficialModelIntoToml"), true);
equal(appTsx.includes("function handleImportOfficialCodexProfileToForm()"), true);
equal(appTsx.includes("nativeCommand.importOfficialCodexProfile"), true);
equal(appTsx.includes("currentCodexLocalProfile ? ("), false);
equal(appTsx.includes("handleSyncCodexProfile"), false);
const codexConfigPanel = readSource("./components/CodexConfigPanel.tsx");
equal(countMatches(appTsx, /handleImportOfficialCodexProfileToForm\(\)/g) >= 2, true);
equal(codexConfigPanel.includes("onImportOfficialProfile"), true);
equal(countMatches(codexConfigPanel, /onClick=\{onImportOfficialProfile\}/g), 1);
equal(codexConfigPanel.includes("同步本机 Codex 配置"), true);
const officialCodexModelField = readSource("./components/OfficialCodexModelField.tsx");
equal(officialCodexModelField.includes("aria-label=\"官方模型候选\""), true);
equal(officialCodexModelField.includes("该模型会写入官方 config.toml 的 model 字段；实际可用性仍以当前 ChatGPT 账号计划和额度为准。"), true);
equal(appTsx.includes("<span className=\"ccr-advanced-summary\">套餐模式无需手动配置</span>"), false);
equal(appTsx.includes("Claude 客户端不支持非官方的模型名称调用，需模型厂商自身有模型映射。"), false);
equal(uiTranslation.includes('"Anthropic 上游地址": "Anthropic Upstream URL"'), true);
equal(uiTranslation.includes('"Claude Desktop 上游地址": "Claude Desktop Upstream URL"'), true);
equal(uiTranslation.includes('"OpenAI Chat 上游地址": "OpenAI Chat Upstream URL"'), true);
equal(uiTranslation.includes('"使用本机 Codex 官方登录，无需填写 API Key 或 Base URL；没有官方账号时可直接使用三方配置。"'), true);
equal(uiTranslation.includes('"模型是否可用，以当前 ChatGPT 套餐、额度和 Codex 模型菜单为准。"'), true);
equal(uiTranslation.includes('"需要刷新 auth.json 或 config.toml 时，请在下方“官方登录配置”中同步。"'), true);
equal(appTsx.includes("Chat Completions 上游地址"), true);
equal(appTsx.includes("Responses 上游地址"), true);
equal(appTsx.includes("该地址只保存为 Switch++ 上游地址；Codex 只读取本地网关"), true);
equal(appTsx.includes("该地址会写入 Codex 专用 custom provider，不影响官方 openai provider。"), true);
equal(appTsx.includes("Codex 三方模式使用专用 provider；本地网关负责记录、认证和统一启停。"), true);
equal(appTsx.includes("Codex 三方模式使用专用 provider；本地网关负责适配上游 Chat Completions。"), true);
equal(appTsx.includes("本地网关"), true);
equal(codexConfigPanel.includes("官方登录配置"), true);
equal(codexConfigPanel.includes("Codex 生效预览"), true);
equal(codexConfigPanel.includes("专用 provider"), true);
equal(codexConfigPanel.includes("生成的三方 provider (TOML)"), true);
equal(codexConfigPanel.includes("这些选项会写入三方专用 provider 配置；认证与官方登录态隔离。"), true);
equal(appTsx.includes("provider 覆盖"), false);
equal(appTsx.includes("生成的 model catalog (JSON)"), false);
equal(codexConfigPanel.includes("三方配置使用独立 custom provider"), true);
equal(codexConfigPanel.includes("model_catalog_json"), false);
equal(codexConfigPanel.includes("不会并入官方账号模型菜单"), true);
equal(codexConfigPanel.includes("由三方模型调用"), false);
equal(uiTranslation.includes('"三方配置使用独立 custom provider'), true);
equal(codexConfigPanel.includes("auth.json 包含登录凭据；仅从本机 Codex 同步，请勿复制或分享。"), true);
equal(appTsx.includes("不会改写官方 auth.json"), true);
equal(appTsx.includes("上游 Responses token 保存在 Switch++ profile 中"), true);
equal(appTsx.includes("本地网关负责把 Responses 请求适配到上游 Chat Completions"), true);
equal(gatewayPage.includes("function codexProfileCanStartPassThroughProxy"), true);
equal(gatewayPage.includes('profile.connection_mode === "official"'), false);
equal(gatewayPage.includes("官方账号观测转发"), false);
equal(gatewayPage.includes("官方观测"), false);
equal(gatewayProxyPanel.includes("开启官方观测网关"), false);
equal(appTsx.includes("开启官方观测网关失败"), false);
equal(appTsx.includes("关闭官方观测网关失败"), false);
equal(appTsx.includes("开启官方请求观测失败"), false);
equal(appTsx.includes("关闭官方请求观测失败"), false);
equal(gatewayPage.includes("function gatewayProfileLabel"), true);
equal(gatewayPage.includes("const profileLabel = gatewayProfileLabel(snapshot);"), true);
equal(gatewayPage.includes("当前应用未配置可启动的网关路径"), true);
equal(gatewayPage.includes("需要或建议使用本地兼容网关"), true);
equal(gatewayPage.includes("为当前客户端应用一个需要本地兼容网关的三方配置后"), false);
equal(gatewaySnapshotUtils.includes("!canStart"), true);
equal(appTsx.includes("Codex 三方厂商连接使用专用 custom provider"), true);
equal(appTsx.includes("直连模式不会经过本地网关，隐藏 think 输出只在开启本地网关后生效。"), false);
equal(appTsx.includes('const codexProfile = profile as CodexProfile;'), true);
equal(appTsx.includes('codexProfile.connection_mode === "official"'), true);
equal(appTsx.includes("使用本机 Codex 官方登录，无需填写 API Key 或 Base URL；默认模型写入 config.toml，可用性以当前 Codex 模型菜单、ChatGPT 套餐和额度为准。"), true);
equal(appTsx.includes("使用本机 Claude 官方登录，无需填写 API Key 或 Base URL。应用后会清除 Switch++ 的网关覆盖，让 Claude Code / Claude Desktop 恢复官方连接。"), true);
equal(vendorPresets.includes("gpt-5.2"), false);
equal(profileFormUtils.includes("gpt-5.2"), false);
equal(configPreviews.includes("gpt-5.2"), false);
equal(appTsx.includes('codexProfile.compat_mode === "proxy" ? ('), true);
equal(appTsx.includes("仅网关模式可剥离 &lt;think&gt; 内容；厂商连接配置不会经过本地网关。"), true);
equal(appTsx.includes('addForm.compat_mode === "proxy" ? ('), true);
equal(appTsx.includes("厂商连接模式不经过本地网关，隐藏 think 输出不可用。"), true);
equal(uiTranslation.includes('"厂商连接模式不经过本地网关，隐藏 think 输出不可用。": "Provider connection mode does not pass through the local gateway'), true);
equal(appTsx.includes("OpenCode 会写入 opencode.json 的 provider/model/small_model"), true);
equal(uiTranslation.includes('"OpenCode 会写入 opencode.json 的 provider/model/small_model；如果已有 Oh My OpenAgent 配置上下文，应用 OpenCode 时会同步刷新 Oh My OpenAgent 路由，避免两个入口各自指向不同模型。": "OpenCode writes provider/model/small_model in opencode.json.'), true);
equal(appTsx.includes("OpenClaw 会写入 openclaw.json 的 models.providers 与 agents.defaults"), true);
equal(uiTranslation.includes('"OpenClaw 会写入 openclaw.json 的 models.providers 与 agents.defaults；预设厂商已内置协议与认证方式，通常只需要填写厂商 API Key 和模型。": "OpenClaw writes models.providers and agents.defaults in openclaw.json.'), true);
equal(appTsx.includes("vendorPresetSourceUrlForTarget"), true);
equal(appTsx.includes("targetProtocolSourceUrl"), true);
equal(appTsx.includes("Hermes 会按官方 Gemini 适配写入 native provider"), true);
equal(appTsx.includes("不会写入 custom_providers"), true);
equal(uiTranslation.includes('"Hermes 会按官方 Gemini 适配写入 native provider：config.yaml 使用 provider=gemini/base_url=原生 Gemini API，API Key 写入 ~/.hermes/.env；不会写入 custom_providers。": "Hermes uses the official Gemini adapter and writes a native provider'), true);
equal(appTsx.includes("自定义配置不会假定协议兼容性；请按模型厂商与目标 agent 官方文档选择 API 格式、认证字段和 Base URL。"), true);
equal(uiTranslation.includes('"按模型厂商与目标 agent 官方文档选择": "Choose according to the model provider and target agent official docs"'), true);
equal(uiTranslation.includes('"用于 Switch++ 连接上游和模型发现；目标 agent 的配置文件会按自身格式写入。": "Used by Switch++ for upstream requests and model discovery; the target agent config is still written in its own file format."'), true);
equal(uiTranslation.includes('"按当前应用官方文档自动勾选稳定项。": "Automatically selects stable options based on the current app'), true);
equal(uiTranslation.includes('"禁用分享": "Disable sharing"'), true);
equal(uiTranslation.includes('"智能审批模式": "Smart approval mode"'), true);
equal(uiTranslation.includes('[/^(.+) 官方选项$/, "$1 Official Options"]'), true);
equal(appTsx.includes("{targetAdvancedProtocolNote}"), true);
equal(appTsx.includes("placeholder={targetBaseUrlPlaceholder}"), true);
equal(appTsx.includes("✓ 已应用"), false);
equal(appTsx.includes("✓ 配置已保存"), false);
equal(appTsx.includes("function switchTargetFromSidebar"), true);
equal(appSidebar.includes("onTargetSelect(option.key)"), true);
equal(appTsx.includes("quitTargetAppAfterApply"), false);
equal(nativeApi.includes("restartTargetApp"), true);
equal(nativeApi.includes("launchCodexPluginUnlocker"), false);
equal(nativeApi.includes("loadCodexUsageQuota"), false);
equal(nativeApi.includes("openSettingsWindow"), false);
equal(appTypes.includes("CodexUsageQuotaWindow"), false);
equal(appTypes.includes("CodexPluginUnlockerLaunchResult"), false);
equal(appTsx.includes('const isUsagePanelWindow = getCurrentWindow().label === "usage";'), false);
equal(appTsx.includes("function activeCodexEnhancementProfile"), false);
equal(appTsx.includes("activeCodexEnhancementProfile()"), false);
equal(appTsx.includes("function appliedCodexProfile"), false);
equal(appTsx.includes("function configuredUsagePanelTargets"), false);
equal(appTsx.includes("onSelectTarget={setUsagePanelTarget}"), false);
equal(appTsx.includes("open-target-settings"), false);
equal(appTsx.includes("const canShowCodexEnhancementAction = isCodexTarget(target)"), false);
equal(appTsx.includes('className="ccr-usage-window"'), false);
equal(appTsx.includes("handleLaunchCodexPluginUnlocker"), false);
equal(appTsx.includes("handleLoadCodexUsageQuota"), false);
equal(appTsx.includes('result.injected ? "success" : result.launched ? "error" : ""'), false);
equal(appTsx.includes("查看官方额度失败"), false);
equal(codexConfigPanel.includes("!isOfficialCodexDirect ? ("), true);
equal(codexConfigPanel.includes("canLaunchCodexEnhancement ? ("), false);
equal(codexConfigPanel.includes("查看官方额度"), false);
equal(codexConfigPanel.includes("codexUsageQuota.windows.map"), false);
equal(appTsx.includes("<CodexUsagePanel"), false);
equal(appTsx.includes("自动重启失败"), false);
equal(appTsx.includes("setView(\"list\")"), true);
equal(appTsx.includes("buildTargetConfigPreview(emptyForm, nextTarget)"), true);
equal(appTsx.includes("const isGeneratedClientConfigTarget = isGatewayTarget && !isClaudeGatewayTarget(target);"), true);
equal(appTsx.includes("const canWriteTargetConfig = supportsNativeApply(target);"), true);
equal(appTsx.includes("readOnly={isGeneratedClientConfigTarget}"), true);
equal(appTsx.includes("disabled={!canWriteTargetConfig}"), true);
equal(appTsx.includes("暂不支持写入该客户端配置"), true);
equal(gatewayConfigOptions.includes("opencodeConfigOptionItems"), true);
equal(gatewayConfigOptions.includes("openclawConfigOptionItems"), true);
equal(gatewayConfigOptions.includes("hermesConfigOptionItems"), true);
equal(appTsx.includes("configOptionItemsForTarget"), true);
equal(appTsx.includes("`${targetDisplayName(target)} 官方选项`"), true);
equal(gatewayConfigOptions.includes("permission.edit"), true);
equal(gatewayConfigOptions.includes("agents.defaults.sandbox.mode"), true);
equal(gatewayConfigOptions.includes("display.streaming"), true);
equal(appTsx.includes("shouldApplyNewClientProfile"), true);
equal(appTsx.includes("!isClaudeGatewayTarget(target)"), true);
equal(appTsx.includes("!isCodexTarget(target)"), true);
equal(appTsx.includes("const nextSupports1m = e.currentTarget.checked;"), false);
equal(appTsx.includes("const checked = Boolean(addForm.supports_1m_context);"), false);
equal(appTsx.includes("addForm.supports_1m_context || catalogSupports1m"), false);
equal(appTsx.includes("supports_1m_context: e.currentTarget.checked"), false);
equal(modelDiscoveryField.includes("e.currentTarget.value"), true);
equal(appTsx.includes("targetUsesAppConfigFields(target)"), true);
equal(appTsx.includes("按当前应用配置文件字段写入默认模型、provider 模型列表与路由模型。"), true);
equal(appTsx.includes("小模型 small_model"), true);
equal(appTsx.includes("标题生成模型"), true);
equal(appTsx.includes("同步 OpenCode 可用模型"), true);
equal(configPreviews.includes("export function buildOpenCodeConfigPreview"), true);
equal(configPreviews.includes("export function buildOpenClawConfigPreview"), true);
equal(configPreviews.includes("export function buildHermesConfigPreview"), true);
equal(configPreviews.includes("export function buildTargetConfigPreview"), true);
equal(configPreviews.includes("opencode_require_approval"), true);
equal(configPreviews.includes("openclaw_sandbox_non_main"), true);
equal(configPreviews.includes("hermes_streaming"), true);
equal(appTsx.includes("resetAddViewForTarget(option.key)"), false);
