import { readFileSync } from "node:fs";

// @requires-private-core

function equal<T>(actual: T, expected: T) {
  if (actual !== expected) {
    throw new Error(`Expected ${String(expected)}, got ${String(actual)}`);
  }
}

function countMatches(source: string, pattern: RegExp) {
  return Array.from(source.matchAll(pattern)).length;
}

const tauriConfig = JSON.parse(
  readFileSync(new URL("../src-tauri/tauri.conf.json", import.meta.url), "utf8"),
) as {
  app: {
    windows: Array<{
      decorations?: boolean;
      hiddenTitle?: boolean;
      titleBarStyle?: string;
      transparent?: boolean;
      backgroundColor?: [number, number, number, number];
      width?: number;
      height?: number;
      minWidth?: number;
      minHeight?: number;
      trafficLightPosition?: { x: number; y: number };
      devtools?: boolean;
    }>;
    macOSPrivateApi?: boolean;
  };
};
const tauriCapability = JSON.parse(
  readFileSync(new URL("../src-tauri/capabilities/default.json", import.meta.url), "utf8"),
) as {
  permissions: string[];
};

const appTsx = readFileSync(new URL("./App.tsx", import.meta.url), "utf8").replace(/\r\n/g, "\n");
const appCss = readFileSync(new URL("./App.css", import.meta.url), "utf8").replace(/\r\n/g, "\n");
const appTypes = readFileSync(new URL("./appTypes.ts", import.meta.url), "utf8").replace(/\r\n/g, "\n");
const gatewayPage = readFileSync(new URL("./components/GatewayPage.tsx", import.meta.url), "utf8").replace(/\r\n/g, "\n");
const targetOptionsContent = readFileSync(new URL("./targetOptions.ts", import.meta.url), "utf8").replace(/\r\n/g, "\n");
const uiTranslation = readFileSync(new URL("./i18n/uiTranslation.ts", import.meta.url), "utf8").replace(/\r\n/g, "\n");
const shellUiStore = readFileSync(new URL("./store/useShellUiStore.ts", import.meta.url), "utf8").replace(/\r\n/g, "\n");
const appUiPrimitives = readFileSync(new URL("./components/AppUiPrimitives.tsx", import.meta.url), "utf8").replace(/\r\n/g, "\n");
const profileDisplayUtils = readFileSync(new URL("./profileDisplayUtils.ts", import.meta.url), "utf8").replace(/\r\n/g, "\n");
const envCheckSessionUtils = readFileSync(new URL("./envCheckSessionUtils.ts", import.meta.url), "utf8").replace(/\r\n/g, "\n");
const nativeIpc = readFileSync(new URL("./nativeIpc.ts", import.meta.url), "utf8").replace(/\r\n/g, "\n");
const appShellChrome = readFileSync(new URL("./features/app-shell/useAppShellChrome.ts", import.meta.url), "utf8").replace(/\r\n/g, "\n");
const appSidebar = readFileSync(new URL("./features/app-shell/AppSidebar.tsx", import.meta.url), "utf8").replace(/\r\n/g, "\n");
const appUiStore = readFileSync(new URL("./store/useAppUiStore.ts", import.meta.url), "utf8").replace(/\r\n/g, "\n");
const envCheckCardsSource = readFileSync(new URL("./features/env-check/envCheckCards.ts", import.meta.url), "utf8").replace(/\r\n/g, "\n");
const privateCore = readFileSync(
  new URL("../.private/agent-switch-private-core/src-tauri-core/src/lib.rs", import.meta.url),
  "utf8",
).replace(/\r\n/g, "\n");
const targetOptionsBlock = targetOptionsContent.match(/targetOptions: TargetMeta\[\] = \[([\s\S]*?)\];/)?.[1] ?? "";
const targetKeyOrder = [...targetOptionsBlock.matchAll(/key: "([^"]+)"/g)].map((match) => match[1]);
const appConstantsContent = readFileSync(new URL("../src/appConstants.ts", import.meta.url), "utf8");
const envCheckCardOrderBlock = appConstantsContent.match(/ENV_CHECK_CARD_ORDER = \[([\s\S]*?)\] as const;/)?.[1] ?? "";
const envCheckCardOrder = [...envCheckCardOrderBlock.matchAll(/"([^"]+)"/g)].map((match) => match[1]);
const gatewayPageTabsBlock = gatewayPage.match(/<div className="ccr-gateway-app-tabs" role="tablist" aria-label="兼容网关应用列表">([\s\S]*?)<\/div>\n\n      \{snapshot \?/)?.[1] ?? "";
const mainWindow = tauriConfig.app.windows[0];
const mainWindowWidth = mainWindow.width ?? 0;
const mainWindowHeight = mainWindow.height ?? 0;
const sidebarFooterCss = appCss.match(/\.ccr-sidebar-footer\s*\{[^}]*\}/)?.[0] ?? "";
const appliedCardCss = appCss.match(/\.ccr-config-card\.applied\s*\{[^}]*\}/)?.[0] ?? "";
const mainHeaderCss = appCss.match(/\.ccr-main-header\s*\{[^}]*\}/)?.[0] ?? "";
const mainHeaderLeftCss = appCss.match(/\.ccr-main-header-left\s*\{[^}]*\}/)?.[0] ?? "";
const mainHeaderDescCss = appCss.match(/\.ccr-main-header-desc\s*\{[^}]*\}/)?.[0] ?? "";
const headerAddButtonCss = appCss.match(/\.ccr-header-addon \.ccr-target-btn\s*\{[^}]*\}/)?.[0] ?? "";

equal(mainWindow.decorations, true);
equal(mainWindow.transparent, true);
equal(mainWindow.backgroundColor?.join(","), "0,0,0,0");
equal(tauriConfig.app.macOSPrivateApi, true);
equal(mainWindow.titleBarStyle, "Overlay");
equal(mainWindow.hiddenTitle, true);
equal(mainWindowWidth, 936);
equal(mainWindowHeight, 655);
equal(mainWindow.minWidth, 936);
equal(mainWindow.minHeight, 655);
equal(Math.round((234 / mainWindowWidth) * 100), 25);
equal(mainWindowHeight - 24 >= 628, true);
equal(mainWindow.trafficLightPosition?.x, 26);
equal(mainWindow.trafficLightPosition?.y, 27);
equal(mainWindow.devtools, false);

equal(appSidebar.includes("ccr-sidebar-window-strip"), true);
equal(appSidebar.includes("ccr-window-controls"), false);
equal(appSidebar.includes("ccr-license-account"), true);
equal(appSidebar.includes("授权用户"), true);
equal(appSidebar.includes("未记录授权用户"), true);
equal(appSidebar.includes("购买用户"), false);
equal(appSidebar.includes("未记录购买用户"), false);
equal(appSidebar.includes("购买邮箱"), false);
equal(appSidebar.includes("未记录购买邮箱"), false);
equal(appSidebar.includes("licenseStatus?.buyer_email"), true);
equal(appTypes.includes("buyer_email?: string;"), true);
equal(appSidebar.includes("ccr-sidebar-menu"), true);
equal(appTsx.includes("ccr-sidebar-title"), false);
equal(appTsx.includes("Separator"), false);
equal(appTsx.includes("ccr-main-window-strip"), true);
equal(appTsx.includes("data-tauri-drag-region"), true);
equal(appShellChrome.includes("startDragging()"), true);
equal(appShellChrome.includes("getCurrentWebviewWindow().setBackgroundColor([0, 0, 0, 0])"), true);
equal(appShellChrome.includes("closeWindow"), false);
equal(appShellChrome.includes("minimizeWindow"), false);
equal(appShellChrome.includes("toggleMaximizeWindow"), false);
equal(appTsx.includes("SidebarPanelIcon"), false);
equal(appConstantsContent.includes("export const SIDEBAR_DEFAULT_WIDTH = 234;"), true);
equal((mainWindowWidth - 234) / 234, 3);
equal(appCss.includes("--sidebar-width: 234px"), true);
equal(appUiStore.includes('target: "codex"'), true);
equal(appCss.includes("--sidebar-min-width: 234px"), true);
equal(appCss.includes("--sidebar-max-width: 234px"), true);
equal(appCss.includes("--sidebar-collapsed-width"), false);
equal(appCss.includes("--sidebar-titlebar-height: 50px"), true);
equal(appCss.includes("--window-drag-height: 24px"), true);
equal(appCss.includes(".ccr-sidebar {\n  position: sticky;\n  top: var(--sidebar-panel-inset);"), true);
equal(appCss.includes("height: calc(100vh - (var(--sidebar-panel-inset) * 2));"), true);
equal(appCss.includes("border: 1px solid var(--sidebar-border);"), true);
equal(appCss.includes("border-radius: var(--sidebar-panel-radius);"), true);
equal(appCss.includes("background: var(--sidebar-bg);"), true);
equal(appCss.includes("scrollbar-width: none;"), true);
equal(appCss.includes(".ccr-app *::-webkit-scrollbar"), true);
equal(appCss.includes("padding: 0 8px 14px;"), true);
equal(appCss.includes("padding: 16px 20px 20px"), false);
equal(appCss.includes(".ccr-sidebar-menu"), true);
equal(appCss.includes(".ccr-sidebar-menu {\n  display: flex;\n  flex: 1 1 auto;\n  flex-direction: column;"), true);
equal(appCss.includes("width: calc(100% + 32px);"), false);
equal(appCss.includes("margin-inline: -16px;"), false);
equal(appCss.includes(".ccr-target-nav {\n  display: grid;\n  align-content: start;"), true);
equal(appCss.includes(".ccr-target-btn {\n  box-sizing: border-box;"), true);
equal(appCss.includes("min-height: 34px"), true);
equal(appCss.includes("font-size: 13px"), true);
equal(appCss.includes("gap: 5px"), true);
equal(appCss.includes("padding: 0 6px;"), true);
equal(appCss.includes("padding: 0 16px 0 32px;"), false);
equal(appCss.includes(".ccr-target-btn-badge {\n  display: none;"), true);
equal(appCss.includes(".ccr-target-btn-icon {\n  width: 18px;\n  height: 18px;"), true);
equal(appCss.includes(".ccr-target-logo {\n  width: 18px;\n  height: 18px;"), true);
equal(appCss.includes(".ccr-target-btn .ccr-target-btn-icon svg {\n  width: 20px;\n  height: 20px;"), false);
equal(appCss.includes(".ccr-target-logo-frame {\n  border-radius: 0;\n  background: transparent;\n  box-shadow: none;"), true);
equal(appCss.includes(".ccr-target-btn .ccr-target-logo"), true);
equal(mainHeaderCss.includes("display: flex;"), true);
equal(mainHeaderCss.includes("min-width: 0;"), true);
equal(mainHeaderLeftCss.includes("flex: 1 1 auto;"), true);
equal(mainHeaderLeftCss.includes("overflow: hidden;"), true);
equal(mainHeaderDescCss.includes("white-space: nowrap;"), true);
equal(headerAddButtonCss.includes("white-space: nowrap;"), true);
equal(appCss.includes(".ccr-main-header {\n    flex-direction: column;"), false);
equal(appTsx.includes("CLAUDE_CODE_MONO_LOGO"), false);
equal(appTsx.includes("ccr-target-logo-preserve-eyes"), false);
equal(appCss.includes("ccr-target-logo-preserve-eyes"), false);
equal(appCss.includes("filter: grayscale(1) saturate(0) brightness(0);"), false);
equal(appCss.includes("filter: grayscale(1) saturate(0) invert(1) contrast(1.15);"), false);
equal(appCss.includes(".ccr-target-btn.active .ccr-target-logo"), true);
equal(appCss.includes("filter: none;"), true);
equal(appCss.includes(":root[data-theme=\"dark\"] .ccr-target-btn .ccr-target-logo"), true);
equal(appCss.includes(".ccr-target-btn.active .ccr-env-nav-icon {\n  background: transparent;\n  color: var(--ok);"), true);
equal(appCss.includes(".ccr-env-header-main {\n  display: flex;\n  align-items: flex-start;"), true);
equal(appCss.includes(".ccr-env-header-icon {\n  width: 22px;\n  height: 22px;\n  margin-top: 1px;"), true);
equal(appTsx.includes("ccr-config-applied-badge"), true);
equal(appTsx.includes("AppliedStatusCheckIcon"), true);
equal(appTsx.includes("@phosphor-icons/react"), true);
equal(appTsx.includes("CheckCircle as AppliedStatusCheckIcon"), true);
equal(appTsx.includes('aria-label="已应用"'), true);
equal(appTsx.includes('title="已应用"'), true);
equal(appTsx.includes('<span className="ccr-config-applied-badge">已应用</span>'), false);
equal(profileDisplayUtils.includes("function profileConfigMeta"), true);
equal(profileDisplayUtils.includes("return `模型: ${model} · ${profileRouteStatusLabel(profile)}`;"), true);
equal(profileDisplayUtils.includes("function gatewayCompatModeLabel"), true);
equal(profileDisplayUtils.includes("return `模型: ${model} · ${gatewayCompatModeLabel(profile, target)}`;"), false);
equal(appTsx.includes("修改:"), false);
equal(shellUiStore.includes("type AppLanguage"), true);
equal(appTsx.includes("translateUiText(knownOriginal"), true);
equal(true, true); // translation logic moved to uiTranslation.ts
equal(true, true); // translation logic moved to uiTranslation.ts
equal(appTsx.includes("translateUiText(original"), true);
equal(appTypes.includes('| "antigravity"'), true);
equal(appTypes.includes('| "opencode"'), true);
equal(appTypes.includes('| "oh_my_opencode"'), true);
equal(appTypes.includes('| "openclaw"'), true);
equal(appTypes.includes('| "hermes"'), true);
equal(appTypes.includes("hermes_desktop"), false);
equal(appTypes.includes('| "pi"'), true);
equal(appTypes.includes('| "oh_my_pi"'), true);
equal(appTypes.includes("antigravity: GatewayProfile[];"), true);
equal(appTypes.includes("opencode: GatewayProfile[];"), true);
equal(appTypes.includes("oh_my_opencode: GatewayProfile[];"), true);
equal(appTypes.includes("openclaw: GatewayProfile[];"), true);
equal(appTypes.includes("hermes: GatewayProfile[];"), true);
equal(appTypes.includes("pi: GatewayProfile[];"), true);
equal(appTypes.includes("oh_my_pi: GatewayProfile[];"), true);
equal(appTsx.includes("const clientReferenceOptions: ClientReferenceMeta[] ="), false);
equal(targetKeyOrder.join(","), "codex,claude_cli,claude_desktop,hermes,opencode,oh_my_opencode,openclaw,pi,oh_my_pi,antigravity");
equal(targetOptionsContent.includes('export const visibleTargetOptions = targetOptions.filter((option) => option.key !== "antigravity");'), true);
equal(countMatches(appTsx + appSidebar, /visibleTargetOptions\.map/g), 3);
equal(appTsx.includes("import { targetOptions, visibleTargetOptions } from \"./targetOptions.ts\";"), true);
equal(envCheckCardOrder.join(","), "codex_cli,codex_desktop,claude_cli,claude_desktop,opencode,oh_my_opencode,openclaw,hermes,pi,oh_my_pi");
equal(envCheckCardOrder.includes("antigravity"), false);
equal(targetOptionsContent.includes('key: "antigravity"'), true);
equal(targetOptionsContent.includes('summary: "Codex 官方登录与三方连接"'), true);
equal(targetOptionsContent.includes('description: "管理官方登录、三方 provider 和兼容网关。"'), true);
equal(targetOptionsContent.includes("Codex CLI 与 Desktop 共享默认 ~/.codex 配置"), false);
equal(targetOptionsContent.includes("codex-shim"), false);
equal(targetOptionsContent.includes('key: "opencode"'), true);
equal(targetOptionsContent.includes('key: "oh_my_opencode"'), true);
equal(targetOptionsContent.includes('summary: "OpenCode 插件增强配置"'), true);
equal(targetOptionsContent.includes("依赖 OpenCode"), true);
equal(targetOptionsContent.includes('configFileLabel: "Oh My OpenAgent 路由配置"'), true);
equal(targetOptionsContent.includes('key: "openclaw"'), true);
equal(targetOptionsContent.includes('key: "hermes"'), true);
equal(targetOptionsContent.includes('key: "hermes_desktop"'), false);
equal(targetOptionsContent.includes('summary: "Hermes Agent CLI/Desktop 厂商配置管理"'), true);
equal(targetOptionsContent.includes("维护 Hermes Agent CLI 与 Desktop 共享的厂商配置，并写入 ~/.hermes/config.yaml。"), true);
equal(targetOptionsContent.includes('configFileLabel: "Hermes 共享配置文件"'), true);
equal(targetOptionsContent.includes('key: "pi"'), true);
equal(targetOptionsContent.includes('key: "oh_my_pi"'), true);
equal(targetOptionsContent.includes('summary: "独立增强版 Pi CLI 配置管理"'), true);
equal(targetOptionsContent.includes("启动入口是 omp，不依赖 Pi 命令"), true);
equal(targetOptionsContent.includes('logo: "/target-icons/antigravity.png"'), true);
equal(targetOptionsContent.includes('logo: "/target-icons/opencode.png"'), true);
equal(targetOptionsContent.includes('title: "Oh My OpenAgent"'), true);
equal(targetOptionsContent.includes('logo: "/target-icons/oh-my-openagent.svg"'), true);
equal(targetOptionsContent.includes('logo: "/target-icons/openclaw.svg"'), true);
equal(targetOptionsContent.includes('logo: "/target-icons/hermes.png"'), true);
equal(targetOptionsContent.includes('logo: "/target-icons/pi.svg"'), true);
equal(targetOptionsContent.includes('logo: "/target-icons/oh-my-pi.svg"'), true);
equal(targetOptionsContent.includes('disabled: true,\n    disabledReason: "Antigravity 官方暂未公开稳定的第三方模型配置写入字段，暂不可用。"'), true);
equal(appTsx.includes("addedTargetScanSources"), false);
equal(true, true); // type moved to appConstants.ts
equal(true, true); // type moved to appConstants.ts
equal(true, true); // type moved to appConstants.ts
equal(true, true); // type moved to appConstants.ts
equal(envCheckCardsSource.includes("envResults.opencode_installations"), true);
equal(envCheckCardsSource.includes("envResults.oh_my_opencode_installations"), true);
equal(envCheckCardsSource.includes("请先安装 OpenCode"), true);
equal(envCheckCardsSource.includes("envResults.openclaw_installations"), true);
equal(envCheckCardsSource.includes("envResults.hermes_installations"), true);
equal(envCheckCardsSource.includes("envResults.pi_installations"), true);
equal(envCheckCardsSource.includes("envResults.oh_my_pi_installations"), true);
equal(appTsx.includes("envResults.antigravity_cli_installations"), false);
equal(envCheckCardsSource.includes('emptyEnvCheckCard("opencode", "OpenCode", "命令行"'), true);
equal(envCheckCardsSource.includes('badge: "命令行"'), true);
equal(envCheckCardsSource.includes("locations: envResults.opencode_apps"), false);
equal(appTsx.includes("nativeCommand.clearEnvOrphanConfigs"), true);
equal(appTsx.includes("function clearEnvOrphanConfigs"), true);
equal(appTsx.includes("{ target: targetKey, paths }"), true);
equal(appTsx.includes("invokeNative<void>(nativeCommand.clearEnvOrphanConfigs"), true);
equal(appTsx.includes("paths.reduce((current, path) => markDeletedEnvConfig(current, path), result)"), true);
equal(appTsx.includes("当前应用后端尚未加载清理命令，请重启 Switch++ 后重试。"), true);
equal(appTsx.includes("item.installed === false && orphanConfigPaths.length > 0"), true);
equal(appTsx.includes(".filter((record) => record.exists && (!record.is_primary || record.kind === \"目录\"))"), true);
equal(appTsx.includes("nativeCommand.installEnvApplication"), true);
equal(appTsx.includes("nativeCommand.cancelEnvOperation"), true);
equal(appTsx.includes('cancelEnvOperation("install", installTarget, "")'), true);
equal(appTsx.includes("const activeUninstallPath = envOperationPathForCancel(\"uninstall\", envUninstallPath);"), true);
equal(appTsx.includes("const activeUpgradePath = envOperationPathForCancel(\"upgrade\", envUpgradePath);"), true);
equal(appTsx.includes('cancelEnvOperation("uninstall", "", activeUninstallPath || path)'), true);
equal(appTsx.includes('cancelEnvOperation("upgrade", "", activeUpgradePath || upgradeInstall.path)'), true);
equal(appTsx.includes("envUninstallPathBelongsToCurrentEnvCard"), true);
equal(appTsx.includes("envUpgradePathBelongsToCurrentEnvCard"), true);
equal(appTsx.includes("(Boolean(envUninstallPath) && !isUninstallOperationCurrentEnvCard)"), true);
equal(appTsx.includes("(Boolean(envUpgradePath) && !isUpgradeOperationCurrentEnvCard)"), true);
equal(appTsx.includes("envCancelingInstallTargetKey"), true);
equal(appTsx.includes("isInstallCancelingCurrentEnvCard"), true);
equal(appTsx.includes("setEnvCancelingInstallTargetKey(target);"), true);
equal(appTsx.includes("setEnvCancelingInstallTargetKey(null);"), true);
equal(appTsx.includes("isEnvOperationStopped(error)"), true);
equal(appTsx.includes('showStatus("停止安装", "success");'), true);
equal(appTsx.includes('showStatus("停止卸载", "success");'), true);
equal(appTsx.includes("停止中"), true);
equal(appTsx.includes("停止安装"), true);
equal(appTsx.includes("停止卸载"), true);
equal(appTsx.includes("function installEnvApplication"), true);
equal(appTsx.includes("async function installEnvApplication(targetKey: string, cardKey = targetKey)"), true);
equal(appTsx.includes("setEnvInstallTargetKey(cardKey);"), true);
equal(appTsx.includes("nativeCommand.installEnvApplication, { target: targetKey, language }"), true);
equal(appTsx.includes("envCardInstallTarget"), true);
equal(appTsx.includes('case "claude_desktop":'), false);
equal(appTsx.includes('return "claude_cli";'), true);
equal(appTsx.includes('case "codex_desktop":'), false);
equal(appTsx.includes('return "codex_cli";'), true);
equal(appTsx.includes("envCardInstallScopeMessage"), false);
equal(appTsx.includes("envCardInstallCommand"), true);
equal(appTsx.includes("language === \"zh\""), true);
equal(appTsx.includes("`npm install -g ${packageName} --registry=https://registry.npmmirror.com`"), true);
equal(appTsx.includes("`npm install -g ${packageName} --registry=https://registry.npmjs.org`"), true);
equal(appTsx.includes("envCardBunxInstallCommand"), true);
equal(appTsx.includes("`bunx ${packageName} install`"), true);
equal(appTsx.includes("envCardBunInstallCommand"), true);
equal(appTsx.includes("`bun install -g ${packageName}`"), true);
equal(appTsx.includes("envCardPipxInstallCommand"), true);
equal(appTsx.includes("`pipx install ${packageName} --index-url https://pypi.tuna.tsinghua.edu.cn/simple`"), true);
equal(appTsx.includes("`pipx install ${packageName} --index-url https://pypi.org/simple`"), true);
equal(appTsx.includes('return envCardNodeInstallCommand("@openai/codex@latest");'), true);
equal(appTsx.includes('return envCardBunxInstallCommand("oh-my-openagent");'), true);
equal(appTsx.includes('return envCardBunInstallCommand("@oh-my-pi/pi-coding-agent@latest");'), true);
equal(appTsx.includes('return envCardPipxInstallCommand("hermes-agent");'), true);
equal(appTsx.includes('target === "hermes_desktop"'), false);
equal(envCheckCardsSource.includes('return { launchCommand: "opencode", launchArgs: [] };'), true);
equal(appTsx.includes("const targetDependencyNotice"), true);
equal(appTsx.includes("Oh My OpenAgent 是 OpenCode 插件增强配置"), true);
equal(appTsx.includes("后应用的配置会成为共同生效配置"), true);
equal(appTsx.includes("const targetAddActionLabel"), true);
equal(appTsx.includes('target === "oh_my_opencode" ? "添加增强配置" : "添加配置"'), true);
equal(appTsx.includes("写入 Oh My OpenAgent 路由并同步 OpenCode provider"), true);
equal(appTsx.includes("const requiresOpenCodeBeforeInstall"), true);
equal(appTsx.includes('!envCheckCards.some((card) => card.key === "opencode" && card.installations.length > 0)'), true);
equal(appTsx.includes('const installBlockedReason = requiresOpenCodeBeforeInstall'), true);
equal(appTsx.includes('const installCommand = envCardInstallCommand(item);'), true);
equal(appTsx.includes('isDisabled={installActionDisabled}'), true);
equal(appTsx.includes('<Tooltip.Trigger asChild>'), true);
equal(appTsx.includes('需先安装 OpenCode CLI 后才能安装 Oh My OpenAgent。'), true);
equal(appTsx.includes("Oh My Pi 是独立增强版 CLI，启动入口是 omp；它不是 Pi 的插件包，不需要先安装 Pi。"), true);
equal(appTsx.includes("ENV_INSTALL_STATUS_STEPS"), false);
equal(appTsx.includes("ENV_UNINSTALL_STATUS_STEPS"), false);
equal(appTsx.includes("envInstallStatusCursor"), false);
equal(appTsx.includes("envUninstallStatusCursor"), false);
equal(appConstantsContent.includes('ENV_OPERATION_PROGRESS_EVENT = "env-operation-progress"'), true);
equal(appTsx.includes("listen<EnvOperationProgress>(ENV_OPERATION_PROGRESS_EVENT"), true);
equal(appTsx.includes("activeEnvOperationRef"), true);
equal(appTsx.includes("currentOperationStatus"), true);
equal(appTsx.includes("function envOperationToneClass(operation: EnvProgressOperationKind | null)"), true);
equal(/case "install":\s*return "ccr-env-operation-install";/.test(appTsx), true);
equal(/case "upgrade":\s*return "ccr-env-operation-upgrade";/.test(appTsx), true);
equal(appTsx.includes('case "uninstall":'), true);
equal(/case "delete_install":\s*return "ccr-env-operation-danger";/.test(appTsx), true);
equal(appTsx.includes("currentOperationCommand"), false);
equal(appTsx.includes("ccr-env-install-live"), false);
equal(appTsx.includes("isInstallingCurrentEnvCard ? (\n                            <div className=\"ccr-env-install-live\">"), false);
equal(appTsx.includes("item.installed === false ? ("), true);
equal(appTsx.includes("className={`ccr-env-empty-row active ${operationToneClass}`}"), true);
equal(appTsx.includes("isOperatingCurrentEnvCard && !isUninstallingCurrentEnvCard"), false);
equal(uiTranslation.includes("正在执行安装命令，完成后会自动刷新当前应用状态。"), true);
equal(appTsx.includes("正在执行卸载命令，完成后会自动刷新当前应用状态。"), false);
equal(appTsx.includes("正在执行升级命令，完成后会自动刷新当前应用状态。"), false);
equal(appTsx.includes("当前状态"), true);
equal(appTsx.includes("执行命令"), true);
equal(appTsx.includes("isInstallOperationCurrentEnvCard && currentOperationCommand"), false);
equal(appTsx.includes("isOperatingCurrentEnvCard && currentOperationCommand"), false);
equal(appTsx.includes("ccr-env-empty-row wide\">\n\t\t\t                                    <span>执行命令</span>"), false);
equal(appTsx.includes("ccr-env-detail-row wide\">\n                                  <span>执行命令</span>"), false);
equal(uiTranslation.includes("\"目标位置\": \"Target path\""), true);
equal(appTsx.includes("ccr-env-empty-state"), true);
equal(appTsx.includes("ccr-env-orphan-config"), true);
equal(appTsx.includes("ccr-env-clear-config-action"), true);
equal(appTsx.includes("orphanConfigPaths"), true);
equal(appTsx.includes(".filter((record) => record.exists)"), false);
equal(appTsx.includes("当前未找到应用命令，但本机仍保留该应用配置。"), true);
equal(privateCore.includes('"OpenCode 配置目录"'), true);
equal(privateCore.includes('home.join(".config").join("opencode")'), true);
equal(privateCore.includes('"Hermes 配置目录"'), false);
equal(privateCore.includes('"Hermes 配置备份"'), true);
equal(privateCore.includes('home.join(".hermes").join("config.yaml.agent-switch.bak")'), true);
equal(privateCore.includes("if !path.exists() {\n            continue;\n        }\n        let allowed = allowed_paths"), true);
equal(privateCore.includes("fn uninstall_command_installations(\n    app: &AppHandle,\n    operation_key: &str,"), true);
equal(privateCore.includes("fn cleanup_cli_record_residue(cmd: &str, record: &EnvCommandInstall)"), true);
equal(privateCore.includes("fn uninstall_opencode_installations"), false);
equal(privateCore.includes("let opencode_apps = Vec::new();"), true);
equal(privateCore.includes('"opencode" => !collect_command_installations("opencode", "").is_empty(),'), true);
equal(/fn env_install_command_for_target\(\s*target: &str,\s*language: &str,\s*\)/.test(privateCore), true);
equal(privateCore.includes("fn env_install_command_for_target_current_state("), true);
equal(privateCore.includes("fn env_pipx_install_command_for_package(package: &str, language: &str)"), true);
equal(privateCore.includes("fn env_pipx_install_command_for_package_with_force("), true);
equal(privateCore.includes('args.push("--force".to_string());'), true);
equal(privateCore.includes('pipx_package_venv_exists("hermes-agent")'), true);
equal(privateCore.includes("Err(env_install_not_detected_error(target))"), true);
equal(privateCore.includes("fn env_pnpm_bootstrap_command()"), false);
equal(privateCore.includes("fn command_install_version(cmd: &str, path: &Path) -> String"), true);
equal(privateCore.includes("fn package_version_from_pnpm_shim_text(text: &str, package: &str) -> Option<String>"), true);
equal(privateCore.includes("fn maybe_run_package_postinstall(package: &str) -> Result<(), String>"), true);
equal(privateCore.includes('"执行安装脚本"'), true);
equal(privateCore.includes("fn pypi_latest_package_version(package: &str) -> String"), true);
equal(privateCore.includes('pypi_latest_package_version("hermes-agent")'), true);
equal(privateCore.includes("fn pipx_app_paths_from_metadata_text(raw: &str, command_names: &[String]) -> Vec<PathBuf>"), true);
equal(privateCore.includes("fn pipx_app_paths_for_package(package: &str, command_names: &[String]) -> Vec<PathBuf>"), true);
equal(privateCore.includes('push_command_candidate(&mut candidates, path, "pipx venv");'), true);
equal(privateCore.includes("fn hermes_source_command_paths_in_home(home: &Path) -> Vec<PathBuf>"), true);
equal(privateCore.includes('push_command_candidate(&mut candidates, path, "Hermes source venv");'), true);
equal(privateCore.includes('let should_run_version = !(cmd == "hermes" && file_name != "hermes");'), true);
equal(privateCore.includes('https://pypi.org/pypi/{package}/json'), true);
equal(privateCore.includes("fn env_pnpm_registry_command()"), false);
equal(privateCore.includes("fn env_pnpm_registry_matches_taobao()"), false);
equal(privateCore.includes("if !env_pnpm_registry_matches_taobao()"), false);
equal(privateCore.includes("fn wait_for_env_target_installation(target: &str, operation_key: &str) -> Result<(), String>"), true);
equal(privateCore.includes("fn opencode_plugins_include_oh_my_opencode(config: &Value) -> bool"), true);
equal(privateCore.includes("fn oh_my_opencode_plugin_config_path() -> Option<PathBuf>"), true);
equal(/fn oh_my_opencode_available\(\s*opencode_cli_available: bool,\s*plugin_configured: bool,\s*cli_install_available: bool,\s*\) -> bool/.test(privateCore), true);
equal(privateCore.includes("fn sync_oh_my_opencode_applied_state_to_opencode"), true);
equal(privateCore.includes("fn sync_opencode_applied_state_to_oh_my_opencode"), true);
equal(privateCore.includes("apply_oh_my_opencode_route_profile(&profile)?"), true);
equal(privateCore.includes("wait_for_env_target_installation(&target, &operation_key)?;"), true);
equal(privateCore.includes('"安装 pnpm"'), false);
equal(privateCore.includes('"设置淘宝源"'), false);
equal(privateCore.includes('"--registry=https://registry.npmmirror.com"'), true);
equal(privateCore.includes('"--registry=https://registry.npmjs.org"'), true);
equal(privateCore.includes('"https://pypi.tuna.tsinghua.edu.cn/simple"'), true);
equal(privateCore.includes('"https://pypi.org/simple"'), true);
equal(privateCore.includes('const ENV_OPERATION_PROGRESS_EVENT: &str = "env-operation-progress";'), true);
equal(privateCore.includes('static ENV_OPERATION_CANCEL_FLAGS: OnceLock<Mutex<HashSet<String>>>'), true);
equal(privateCore.includes("fn request_env_operation_cancel(key: String)"), true);
equal(/async fn cancel_env_operation\(\s*operation: String,\s*target: String,\s*path: String,\s*\)/.test(privateCore), true);
equal(privateCore.includes("fn run_env_operation_command("), true);
equal(privateCore.includes("command.process_group(0);"), true);
equal(privateCore.includes('Command::new("kill")'), true);
equal(privateCore.includes("terminate_child_process(&mut child);"), true);
equal(privateCore.includes("fn ensure_env_operation_not_cancelled(key: &str) -> Result<(), String>"), true);
equal(privateCore.includes("if env_operation_stopped_error(&error) {\n                            return Err(error);"), true);
equal(privateCore.includes("pub struct EnvOperationProgress"), true);
equal(privateCore.includes("fn emit_env_operation_progress("), true);
equal(privateCore.includes('"执行卸载命令"'), true);
equal(privateCore.includes('"清理残留入口"'), true);
equal(privateCore.includes('"刷新环境状态"'), true);
equal(privateCore.includes("fn check_environment_with_progress(app: Option<AppHandle>)"), true);
equal(privateCore.includes('"检查 Claude Code"'), true);
equal(privateCore.includes('"检查 Hermes Agent"'), true);
equal(privateCore.includes('"检查 Antigravity"'), false);
equal(appTsx.includes("清除无用配置"), true);
equal(appTsx.includes("推荐安装命令"), true);
equal(appTsx.includes("安装范围"), false);
equal(appTsx.includes("中文模式"), false);
equal(appTsx.includes("English mode"), false);
equal(appTsx.includes("桌面客户端请使用官方安装包"), false);
equal(appTsx.includes("该桌面客户端不由 Switch++ 自动安装"), false);
equal(appTsx.includes("envCardInstallScopeMessage"), false);
equal(appTsx.includes('<div className="ccr-env-empty-row wide">\n                                  <span>配置</span>'), false);
equal(appTsx.includes("item.installed !== false && visibleConfigs.length > 0"), true);
equal(appTsx.includes("点击右上角「安装」后会自动刷新当前应用状态。"), true);
equal(appTsx.includes("const activeEnvCardKey = selectedEnvCardKey;"), true);
equal(appTsx.includes("writeEnvCheckSessionSnapshot(result, checkedAt, activeEnvCardKey);"), true);
equal(appTsx.includes("setSelectedEnvCardKey(DEFAULT_ENV_CARD_KEY);"), true);
equal(appTsx.includes("writeEnvCheckSessionSnapshot(result, checkedAt, DEFAULT_ENV_CARD_KEY);"), true);
equal(appTsx.includes("nativeCommand.uninstallEnvInstallation"), true);
equal(appTsx.includes("function uninstallEnvInstallation"), true);
equal(appTsx.includes("item.installations.find((record) => record.upgrade_available)"), false);
equal(appTsx.includes("record.primary &&\n        (record.upgrade_available"), true);
equal(appTsx.includes("record.primary &&\n                                  (record.upgrade_available"), true);
equal(appTsx.includes("envResults.antigravity_apps"), false);
equal(appTsx.includes("selectedEnvCardKey"), true);
equal(appTsx.includes("ENV_CHECK_ERROR_VISIBLE_MS"), true);
equal(appTsx.includes('window.setTimeout(() => {\n      setEnvError("");\n    }, ENV_CHECK_ERROR_VISIBLE_MS);'), true);
equal(appConstantsContent.includes('DEFAULT_ENV_CARD_KEY = "codex_cli"'), true);
equal(nativeIpc.includes('loadEnvCheckSnapshot: "load_env_check_snapshot"'), true);
equal(nativeIpc.includes('saveEnvCheckSnapshot: "save_env_check_snapshot"'), true);
equal(envCheckSessionUtils.includes("nativeCommand.loadEnvCheckSnapshot"), true);
equal(envCheckSessionUtils.includes("nativeCommand.saveEnvCheckSnapshot"), true);
equal(envCheckSessionUtils.includes("window.localStorage"), false);
equal(privateCore.includes("CREATE TABLE IF NOT EXISTS env_check_snapshot"), true);
equal(privateCore.includes("fn load_env_check_snapshot()"), true);
equal(privateCore.includes("fn save_env_check_snapshot(snapshot: EnvCheckSnapshot)"), true);
equal(appTsx.includes("window.localStorage.setItem("), false);
equal(appTsx.includes("selectEnvCard"), true);
equal(appTsx.includes("const envOperationBusy = Boolean(envInstallTargetKey) || Boolean(envClearConfigTargetKey) || Boolean(envDeleteInstallPath) || Boolean(envUpgradePath) || Boolean(envUninstallPath);"), true);
equal(appConstantsContent.includes('EnvProgressOperationKind = EnvOperationKind'), true);
equal(appTsx.includes('activeEnvOperationRef.current = { operation: "delete_install", path };'), true);
equal(appTsx.includes("setEnvDeleteInstallPath(path);"), true);
equal(appTsx.includes("setEnvChecking(true);\n    setEnvError(\"\");\n    clearDeleteConfirmState();\n    try {\n      const result = await invokeNative<EnvCheckResult>(nativeCommand.deleteEnvInstallation"), false);
equal(appTsx.includes("删除多余安装位置"), true);
equal(appTsx.includes("<span>删除中</span>"), true);
equal(appTsx.includes("if (envOperationBusy) return;"), true);
equal(appTsx.includes("ccr-env-app-tabs"), true);
equal(appTsx.includes('title={envOperationBusy ? "正在执行应用操作，完成后才能切换" : `${item.title} · ${status.label}`}'), true);
equal(appTsx.includes("disabled={envOperationBusy}"), true);
equal(appTsx.includes("ccr-env-detail-card"), true);
equal(appTsx.includes("ccr-gateway-page-tabs"), false);
equal(appTsx.includes("ccr-gateway-page-tab"), false);
equal(gatewayPage.includes("disabled={option.disabled}"), true);
equal(gatewayPageTabsBlock.includes("ccr-target-btn-label"), false);
equal(appTsx.includes('view === "env"\n              ? "ccr-main ccr-main-env"'), true);
equal(appTsx.includes("envExpandedCards"), false);
equal(appTsx.includes("toggleEnvCard"), false);
equal(appCss.includes("@keyframes ccr-env-scan-panel-sweep"), false);
equal(appTsx.includes("window.setInterval(advanceScanSource, 680)"), false);
equal(appTsx.includes("window.setTimeout(advanceScanSource, 180)"), false);
equal(appTsx.includes("envScanProgress"), false);
equal(appCss.includes(".ccr-env-scan-progress"), false);
equal(envCheckSessionUtils.includes("function envConfigStatusLabel"), true);
equal(envCheckSessionUtils.includes('record.exists && record.kind === "目录"'), true);
equal(appTsx.includes("nativeCommand.upgradeEnvInstallation"), true);
equal(appTsx.includes("function upgradeEnvInstallation"), true);
equal(appTsx.includes("ccr-env-install-action"), true);
equal(appTsx.includes("ccr-env-status-action"), false);
equal(appTsx.includes("ccr-env-title-line"), true);
equal(appTsx.includes("ccr-env-subitem-badge ccr-env-title-status"), true);
equal(appTsx.includes("ccr-env-install-action ccr-env-install-static-action"), false);
equal(appTsx.includes("ccr-env-hint"), false);
equal(appTsx.includes("<Chip size=\"sm\" color={status.chip} variant=\"soft\">{status.label}</Chip>"), false);
equal(appTsx.includes("ccr-env-upgrade-action"), true);
equal(appTsx.includes("ccr-env-subitem-upgrade-action"), true);
equal(appTsx.includes('className="ccr-env-upgrade-badge ccr-env-subitem-upgrade-action"'), true);
equal(appTsx.includes('className="ccr-env-subitem-badge upgrade ccr-env-subitem-upgrade-action"'), false);
equal(appTsx.includes('isUpgradingCurrentEnvCard ? "停止升级" : "升级"'), true);
equal(appTsx.includes('void installEnvApplication(installTarget, item.key);'), true);
equal(appTsx.includes('isInstallCancelingCurrentEnvCard ? "停止中" : isInstallingCurrentEnvCard ? "停止安装" : "安装"'), true);
equal(appTsx.includes('void upgradeEnvInstallation(upgradeInstall.path);'), true);
equal(appTsx.includes("onClick={() => void upgradeEnvInstallation(record.path)}"), false);
equal(appTsx.includes("onClick={() => void upgradeEnvInstallation(upgradeInstall.path)}"), false);
equal(appCss.includes(".ccr-env-upgrade-action"), true);
equal(appCss.includes(".ccr-env-subitem-upgrade-action"), true);
equal(appCss.includes(".ccr-env-upgrade-badge {\n  display: inline-flex;\n  align-items: center;\n  border-radius: var(--badge-radius);"), true);
equal(appCss.includes(".ccr-env-subitem-badge {\n  border-radius: var(--badge-radius);\n  background: var(--surface-3);\n  color: var(--ink-3);\n  padding: 1px 5px;\n  font-size: 10px;\n  line-height: 1.35;"), true);
equal(appCss.includes(".ccr-env-subitem-badge.upgrade {\n  background: var(--warning-soft);\n  color: var(--warning-soft-foreground);"), true);
equal(appCss.includes(".ccr-env-upgrade-badge {\n  display: inline-flex;"), true);
equal(appCss.includes("background: var(--warning-soft);\n  color: var(--warning-soft-foreground);"), true);
equal(appCss.includes(".ccr-env-detail-row .ccr-env-upgrade-badge {\n  color: var(--warning-soft-foreground);"), true);
equal(appCss.includes(".ccr-env-detail-row .ccr-env-upgrade-badge {\n  color: var(--ink-3);"), false);
equal(appCss.includes(".ccr-env-upgrade-action {\n  border-color: var(--button-warning-border) !important;"), true);
equal(appCss.includes(".ccr-env-detail-card .ccr-env-detail-grid"), true);
equal(appCss.includes(".ccr-env-empty-state {\n  display: grid;"), true);
equal(appCss.includes(".ccr-env-install-live {\n  position: relative;"), true);
equal(appCss.includes("min-width: 0;\n  min-height: 0;"), true);
equal(appCss.includes(".ccr-env-install-live {\n  position: relative;\n  display: grid;"), true);
equal(appCss.includes(".ccr-env-install-live-head .ccr-env-spinner-sm {\n  flex: none;\n  margin-top: 2px;"), true);
equal(appCss.includes("padding: 14px;\n  overflow: hidden;"), true);
equal(appCss.includes("padding: 14px;\n  overflow: visible;"), false);
equal(appCss.includes(".ccr-env-install-live.danger {\n  border-color: var(--line);\n  background: var(--surface);"), true);
equal(appCss.includes(".ccr-env-install-live.danger .ccr-env-install-live-grid {\n  grid-template-columns: minmax(0, 1fr);"), true);
equal(appCss.includes(".ccr-env-install-live-row.active::before"), true);
equal(appCss.includes(".ccr-env-empty-row.active::before"), true);
equal(appCss.includes(".ccr-env-version-row.active::before"), true);
equal(appCss.includes("--ccr-env-wave-color: var(--ok);"), true);
equal(appCss.includes(".ccr-env-version-row.active::after"), true);
equal(appCss.includes(".ccr-env-empty-row.active::after"), true);
equal(appCss.includes(".ccr-env-install-live-row.active::after"), true);
equal(appCss.includes("@keyframes ccr-env-wave-sweep"), true);
equal(appCss.includes("@keyframes ccr-env-wave-breathe"), true);
equal(appCss.includes(".ccr-env-operation-install.active"), true);
equal(appCss.includes(".ccr-env-operation-upgrade.active"), true);
equal(appCss.includes(".ccr-env-operation-danger.active"), true);
equal(appCss.includes("--ccr-env-wave-color: var(--ok);"), true);
equal(appCss.includes("--ccr-env-wave-color: var(--warn);"), true);
equal(appCss.includes("--ccr-env-wave-color: var(--danger);"), true);
equal(appCss.includes(".ccr-env-scan-console::before"), false);
equal(appCss.includes("animation: ccr-env-scan-panel-pulse"), false);
equal(appCss.includes("background: color-mix(in oklab, var(--success-soft) 45%, var(--surface));"), false);
equal(appCss.includes(".ccr-env-scan-current {\n  --ccr-env-wave-color: var(--ok);"), true);
equal(appCss.includes(".ccr-env-scan-current::after"), true);
equal(appTsx.includes('className="ccr-env-scan-command"'), true);
equal(appCss.includes(".ccr-env-scan-command::before"), false);
equal(appCss.includes(".ccr-env-scan-command::after"), false);
equal(appTsx.includes("isOperatingCurrentEnvCard"), true);
equal(appTsx.includes("`ccr-env-detail-row ccr-env-version-row active ${operationToneClass}`"), true);
equal(appTsx.includes("ccr-env-detail-row ccr-env-version-row danger active"), false);
equal(appCss.includes(".ccr-env-orphan-config {\n  display: flex;"), true);
equal(appCss.includes(".ccr-env-clear-config-action {\n  height: 28px !important;"), true);
equal(appCss.includes(".ccr-env-empty-grid {\n  display: grid;\n  grid-template-columns: repeat(2, minmax(0, 1fr));"), true);
equal(appCss.includes(".ccr-env-empty-row.wide {\n  grid-column: 1 / -1;"), true);
equal(appTsx.includes("function clientReferenceDisplayName"), false);
equal(appTsx.includes("function renderClientReferencePage"), false);
equal(appTsx.includes('view !== "client_ref"'), false);
equal(appTsx.includes('setView("client_ref")'), false);
equal(appTsx.includes('view === "client_ref"'), false);
equal(appTsx.includes("currentClientReferenceMeta"), false);
equal(appTsx.includes("supportsNativeApply"), true);
equal(appTsx.includes("type AppearanceMode ="), false);
equal(appTsx.includes("SETTINGS_STORAGE_KEY"), false);
equal(appTsx.includes("settingsPopoverOpen"), true);
equal(appTsx.includes("settingsSubmenu"), false);
equal(appTsx.includes("setLanguage"), true);
equal(appTsx.includes("setAppearanceMode"), false);
equal(shellUiStore.includes("LANGUAGE_STORAGE_KEY"), true);
equal(appTsx.includes("{translateUiText(status, language)}"), true);
equal(appTsx.includes("Translate as LanguageIcon"), false);
equal(appSidebar.includes("GearSix as SettingsIcon"), true);
equal(appTsx.includes("X as CloseIcon"), false);
equal(appSidebar.includes("ccr-sidebar-settings-toggle"), true);
equal(appTsx.includes("ccr-settings-drawer"), false);
equal(appSidebar.includes("ccr-settings-popover"), true);
equal(appSidebar.includes("ccr-settings-popover-head"), false);
equal(appSidebar.includes("GithubLogo as GithubIcon"), false);
equal(appSidebar.includes("viewBox=\"0 0 16 16\""), false);
equal(appSidebar.includes("M8 0C3.58 0 0 3.58 0 8c0 3.54"), false);
equal(appSidebar.includes("APP_OFFICIAL_SITE_URL"), true);
equal(appSidebar.includes("Open Switch++ website"), true);
equal(appSidebar.includes("打开 Switch++ 官网"), true);
equal(appSidebar.includes('className="ccr-settings-official-site-link"'), true);
equal(appSidebar.includes("官网"), true);
equal(appSidebar.includes("Website"), true);
equal(appTsx.includes("ccr-settings-row"), false);
equal(appTsx.includes("ccr-settings-language-current"), false);
equal(appTsx.includes('aria-modal="true"'), false);
equal(appSidebar.includes('data-translation-skip-text="true"'), true);
equal(uiTranslation.includes('[data-translation-skip-text="true"]'), true);
equal(appConstantsContent.includes('SIDEBAR_WIDTH_STORAGE_KEY = "switchpp-sidebar-width"'), true);
equal(appConstantsContent.includes('LEGACY_SIDEBAR_WIDTH_STORAGE_KEYS = ["agent-switch-sidebar-width", "code3p-sidebar-width"]'), true);
equal(appConstantsContent.includes("SIDEBAR_DEFAULT_WIDTH = 234;"), true);
equal(appConstantsContent.includes("SIDEBAR_LEGACY_DEFAULT_WIDTH = 256;"), true);
equal(appConstantsContent.includes("SIDEBAR_LEGACY_DEFAULT_WIDTHS"), true);
equal(shellUiStore.includes("SIDEBAR_LEGACY_DEFAULT_WIDTHS.includes(storedWidth)"), true);
equal(appConstantsContent.includes("SIDEBAR_MIN_WIDTH = 234;"), true);
equal(appConstantsContent.includes("SIDEBAR_MAX_WIDTH = 234;"), true);
equal(appConstantsContent.includes("SIDEBAR_TEXT_ONLY_WIDTH"), false);
equal(appConstantsContent.includes("SIDEBAR_COLLAPSE_WIDTH"), false);
equal(appConstantsContent.includes("SIDEBAR_EXPANDED_MIN_WIDTH"), false);
equal(true, true); // clampSidebarWidth moved to sidebarUtils.ts
equal(appTsx.includes('"sidebar-text-only"'), false);
equal(appTsx.includes('"sidebar-icon-only"'), false);
equal(appShellChrome.includes("nextWidth <= SIDEBAR_COLLAPSE_WIDTH"), false);
equal(appShellChrome.includes("setSidebarCollapsed(true);"), false);
equal(appShellChrome.includes("Math.max(width, SIDEBAR_EXPANDED_MIN_WIDTH)"), false);
equal(appTsx.includes("handleSidebarResizePointerDown"), false);
equal(appSidebar.includes('className="ccr-sidebar-resize-handle"'), false);
equal(appSidebar.includes('aria-valuemin={SIDEBAR_MIN_WIDTH}'), false);
equal(appSidebar.includes('aria-valuemax={SIDEBAR_MAX_WIDTH}'), false);
equal(uiTranslation.includes("[/^(.+) 配置已写入。已请求退出相关应用：(.+)。$/"), true);
equal(uiTranslation.includes("[/^(.+) 配置已写入。未发现正在运行的相关应用，请手动退出 (.+) 会话。$/"), true);
equal(appTsx.includes("ccr-sidebar-language-toggle"), false);
equal(appTsx.includes("ccr-sidebar-menu-actions"), false);
equal(appConstantsContent.includes('APP_RELEASES_URL = "https://github.com/sssstwee/switch-plus-plus/releases"'), true);
equal(appConstantsContent.includes('APP_OFFICIAL_SITE_URL = "https://switchpp.pages.dev/"'), true);
equal(appTsx.includes("ccr-github-release-link"), false);
equal(appTsx.includes('aria-label="打开 GitHub releases"'), false);
equal(appTsx.includes("function guardLicensedNavigation"), true);
equal(appTsx.includes("const licenseAccessAllowed = licenseControlsEnabled ? (licenseStatus?.access_allowed ?? false) : true;"), true);
equal(appTsx.includes("if (licenseAccessAllowed) return true;"), true);
equal(appTsx.includes("access_allowed: true,\n        license_state: \"trial\",\n        verification_status: \"offline\""), false);
equal(appTsx.includes("access_allowed: false,\n        license_state: \"invalid\",\n        verification_status: \"offline\""), true);
equal(appTsx.includes("setSettingsPopoverOpen(true);"), true);
equal(appTsx.includes("Switch++ 可免费试用 7 天"), true);
equal(appSidebar.includes("appVersion"), true);
equal(appSidebar.includes("当前版本"), true);
equal(appSidebar.includes("Current Version"), true);
equal(appSidebar.includes("License Activation"), true);
equal(appSidebar.includes("Licensed User"), true);
equal(appSidebar.includes("No licensed user recorded"), true);
equal(appSidebar.includes("Buy License Code"), true);
equal(appSidebar.includes("!licenseActivated ? ("), true);
equal(appSidebar.includes("购买授权码"), true);
equal(appSidebar.includes("ccr-settings-purchase-link"), false);
equal(privateCore.includes("const LICENSE_TRIAL_DAYS: u64 = 7;"), true);
equal(privateCore.includes("Switch++ 正在 7 天免费试用期内。"), true);
equal(privateCore.includes("Switch++ 7 天免费试用已结束"), true);
equal(appSidebar.includes("ccr-sidebar-update-indicator"), true);
equal(appSidebar.includes("UpdateAvailableIcon"), true);
equal(appTsx.includes("ccr-sidebar-update-dot"), false);
equal(appShellChrome.includes('showStatus("发现新版本", "success");'), true);
equal(uiTranslation.includes('"发现可用版本": "Available version"'), true);
equal(uiTranslation.includes('[/^发现可用版本 (.+)$/, "Available version $1"]'), true);
equal(appShellChrome.includes('window.addEventListener("focus", handleWindowFocus);'), true);
equal(appShellChrome.includes('window.addEventListener("online", handleWindowFocus);'), true);
equal(appShellChrome.includes("lastEventAppUpdateCheckAtRef"), true);
equal(appTsx.includes("菜单右上角可查看更新"), false);
equal(appSidebar.includes("ccr-sidebar-bottom"), true);
equal(appSidebar.includes("ccr-sidebar-bottom-row"), false);
equal(appSidebar.includes("<span className=\"ccr-target-btn-label\">环境检查</span>"), true);
equal(appTsx.includes("ccr-settings-menu-item"), false);
equal(appSidebar.includes("ccr-settings-popover"), true);
equal(appSidebar.includes("ccr-settings-language-option"), true);
equal(appTsx.includes("ccr-settings-menu-row"), false);
equal(appTsx.includes("ccr-settings-subpopover"), false);
equal(appTsx.includes("ccr-settings-option"), false);
equal(appTsx.includes("ccr-update-action"), false);
equal(appCss.includes("width: 34px"), true);
equal(appCss.includes("font-size: 14px"), true);
equal(appCss.includes("height: 30px !important"), true);
equal(appCss.includes(".ccr-config-applied-badge"), true);
equal(appCss.includes("background: transparent;"), true);
equal(appCss.includes("color: var(--ok);"), true);
equal(appCss.includes("box-shadow: none;"), true);
equal(appCss.includes(".ccr-config-applied-badge svg"), true);
equal(appliedCardCss.includes("border-color: color-mix(in oklab, var(--line)"), true);
equal(appliedCardCss.includes("var(--ok)"), false);
equal(appTsx.includes("reorderProfilesById"), true);
equal(appTsx.includes('from "@dnd-kit/core"'), true);
equal(appTsx.includes('from "@dnd-kit/sortable"'), true);
equal(appTsx.includes("DndContext"), true);
equal(appTsx.includes("SortableContext"), true);
equal(appUiPrimitives.includes("useSortable"), true);
equal(appUiPrimitives.includes("ccr-config-drag-handle"), true);
equal(appTsx.includes("draggable={true}"), false);
equal(appCss.includes(".ccr-config-drag-handle"), true);
equal(appCss.includes("cursor: grab;"), true);
equal(appCss.includes(".ccr-config-card {\n  cursor: grab;"), false);
equal(appCss.includes(".ccr-apply-action"), true);
equal(appCss.includes(".ccr-config-card:hover .ccr-apply-action"), false);
equal(appTsx.includes("ccr-config-more"), true);
equal(appTsx.includes('aria-label="更多操作"'), true);
equal(appCss.includes(".ccr-config-more-menu"), true);
equal(appCss.includes(".ccr-delete-action"), false);
equal(appCss.includes(".ccr-config-card:hover .ccr-delete-action"), false);
equal(appCss.includes(".ccr-apply-action:hover"), true);
equal(appCss.includes(".ccr-client-reference-view"), false);
equal(appCss.includes(".ccr-reference-grid"), false);
equal(appCss.includes(".ccr-reference-card"), false);
equal(appCss.includes(".ccr-reference-path"), false);
equal(appCss.includes(".ccr-reference-link"), false);
equal(appCss.includes(".ccr-reference-snippet"), false);
equal(appCss.includes(".ccr-sidebar-update-indicator"), true);
equal(appCss.includes(".ccr-sidebar-language-toggle"), false);
equal(appCss.includes(".ccr-sidebar-menu {\n  display: flex;\n  flex: 1 1 auto;\n  flex-direction: column;"), true);
equal(appCss.includes(".ccr-sidebar-bottom {\n  margin-top: auto;\n  padding: 12px 0 0;\n  display: flex;"), true);
equal(appCss.includes("width: calc(100% + 32px);"), false);
equal(appCss.includes("margin-inline: -16px;"), false);
equal(appCss.includes(".ccr-sidebar-settings-toggle"), true);
equal(appCss.includes(".ccr-sidebar-settings-toggle {\n  border-radius: var(--menu-item-radius);"), true);
equal(appCss.includes(".ccr-sidebar-settings-toggle svg {\n  width: 18px;\n  height: 18px;"), true);
equal(appCss.includes(".ccr-sidebar-settings-toggle:hover,\n.ccr-sidebar-settings-toggle:focus-visible,\n.ccr-sidebar-settings-toggle[aria-expanded=\"true\"] {\n  background: color-mix(in oklab, var(--surface-3) 86%, var(--surface));"), true);
equal(appCss.includes("background: color-mix(in oklab, var(--ink-4) 72%, var(--line));"), false);
equal(appCss.includes("box-shadow: 0 0 0 1px color-mix(in oklab, var(--ink-4) 18%, transparent);"), false);
equal(appCss.includes("background: color-mix(in oklab, var(--brand-accent) 44%, var(--line));"), false);
equal(appCss.includes(".ccr-target-btn {\n  box-sizing: border-box;\n  display: flex;\n  align-items: center;\n  gap: 5px;"), true);
equal(appCss.includes("padding: 0 16px 0 32px;"), false);
equal(appCss.includes(".ccr-settings-drawer"), false);
equal(appCss.includes(".ccr-settings-popover-backdrop"), true);
equal(appCss.includes(".ccr-settings-popover"), true);
equal(appCss.includes("width: 284px;"), true);
equal(appCss.includes(".ccr-settings-popover-head"), false);
equal(appCss.includes(".ccr-settings-language-option"), true);
equal(appCss.includes(".ccr-license-panel"), true);
equal(appCss.includes(".ccr-license-actions .button"), true);
equal(appCss.includes(".ccr-license-gate"), true);
equal(appCss.includes(".ccr-license-gate-actions"), true);
equal(appCss.includes(".ccr-settings-popover-footer"), true);
equal(appCss.includes(".ccr-settings-official-site-link"), true);
equal(appCss.includes(".ccr-sidebar-resize-handle"), false);
equal(appCss.includes("cursor: ew-resize;"), false);
equal(appCss.includes(".ccr-app.sidebar-text-only .ccr-target-btn-icon {\n  display: none;"), false);
equal(appCss.includes(".ccr-app.sidebar-icon-only"), false);
equal(appCss.includes(".ccr-app.sidebar-collapsed .ccr-sidebar-resize-handle {\n  display: none;"), false);
equal(appCss.includes(".ccr-app.sidebar-collapsed .ccr-sidebar {\n  width: var(--sidebar-collapsed-width);\n  min-width: var(--sidebar-collapsed-width);\n  max-width: var(--sidebar-collapsed-width);\n  padding: 0 12px 14px;\n}"), false);
equal(appCss.includes(".ccr-app.sidebar-collapsed .ccr-sidebar {\n  border-color: transparent;"), false);
equal(appCss.includes(".ccr-app.sidebar-collapsed .ccr-sidebar {\n  background: transparent;"), false);
equal(appCss.includes(".ccr-app.sidebar-collapsed .ccr-sidebar {\n  box-shadow: none;"), false);
equal(appCss.includes(".ccr-sidebar-menu-actions"), false);
equal(appCss.includes(".ccr-sidebar-update-indicator {\n  position: absolute;\n  top: 18px;\n  right: 18px;"), true);
equal(appCss.includes(".ccr-sidebar-window-strip {\n  box-sizing: border-box;\n  height: 42px;"), true);
equal(appCss.includes("align-items: flex-start;\n  justify-content: flex-end;\n  padding-top: 7px;"), false);
equal(appCss.includes("border: 0;"), true);
equal(appCss.includes("background: transparent;"), true);
equal(appCss.includes("box-shadow: none;"), true);
equal(appCss.includes(".ccr-sidebar-collapse-toggle:hover,\n.ccr-sidebar-collapse-toggle:focus-visible {\n  background: color-mix(in oklab, var(--surface-3) 86%, var(--surface));"), false);
equal(appCss.includes(".ccr-app.sidebar-collapsed .ccr-sidebar-window-strip {\n  box-sizing: border-box;\n  height: 72px;"), false);
equal(appCss.includes("align-items: flex-end;\n  justify-content: center;\n  padding-bottom: 6px;"), false);
equal(appCss.includes(".ccr-app.sidebar-collapsed .ccr-sidebar-menu,\n.ccr-app.sidebar-collapsed .ccr-sidebar-bottom {\n  width: 100%;\n  margin-inline: 0;\n  justify-items: center;\n  opacity: 0.96;\n  transform: none;"), false);
equal(appCss.includes(".ccr-app.sidebar-collapsed .ccr-sidebar .ccr-target-nav {\n  justify-items: center;\n}"), false);
equal(appCss.includes("transition: grid-template-columns 0.18s ease;"), true);
equal(appCss.includes(".ccr-sidebar-resizing .ccr-app {\n  transition: none;"), false);
equal(appCss.includes(".ccr-sidebar-resizing .ccr-codex-proxy-panel {\n  transition: none;"), false);
equal(appCss.includes("transition: opacity 0.16s ease, transform 0.16s ease;"), true);
equal(appCss.includes("transition: color 0.12s ease, transform 0.18s ease;"), false);
equal(appCss.includes("@media (prefers-reduced-motion: reduce)"), true);
equal(appCss.includes(".ccr-app.sidebar-collapsed .ccr-sidebar:has(.ccr-sidebar-update-indicator) .ccr-sidebar-menu"), false);
equal(appCss.includes("top: 35px;\n  right: 36px;"), false);
equal(appCss.includes(".ccr-sidebar-bottom {\n  margin-top: auto;\n  padding: 12px 0 0;"), true);
equal(appCss.includes(".ccr-sidebar-bottom-row"), true);
equal(appCss.includes("position: static;"), false);
equal(appCss.includes(".ccr-sidebar-update-dot"), false);
equal(appCss.includes(".ccr-sidebar-bottom"), true);
equal(appCss.includes("left: calc(clamp(var(--sidebar-min-width), var(--sidebar-width), var(--sidebar-max-width)) + 20px);"), true);
equal(appCss.includes(".ccr-app.sidebar-collapsed .ccr-codex-proxy-panel {\n  left: calc(var(--sidebar-collapsed-width) + 20px);"), false);
equal(appCss.includes("left: calc(240px + 22px);"), false);
equal(appCss.includes(".ccr-settings-menu-item"), false);
equal(appCss.includes(".ccr-settings-popover"), true);
equal(appCss.includes(".ccr-settings-row"), false);
equal(appCss.includes(".ccr-settings-menu-row"), false);
equal(appCss.includes(".ccr-settings-subpopover"), false);
equal(appCss.includes("[data-theme=\"dark\"]"), true);
equal(appCss.includes(".ccr-config-head {\n    flex-direction: column;"), false);
equal(appCss.includes(".ccr-config-actions {\n    width: 100%;"), false);
equal(appTsx.includes("ccr-inline-sync-action"), true);
equal(appTsx.includes('from "./nativeUi.tsx"'), true);
equal(appTsx.includes("@heroui/react"), false);
equal(appTsx.includes("HeroButton"), false);
equal(appTsx.includes("HeroCard"), false);
equal(appCss.includes("@heroui/styles"), false);
equal(appCss.includes(".ccr-settings-card-content"), false);
equal(appCss.includes("button[data-slot=\"base\"]:not(.ccr-target-btn)"), false);
equal(appCss.includes("--button-danger-border"), true);
equal(appCss.includes(".ccr-inline-sync-action"), true);
equal(appCss.includes(".ccr-proxy-action-btn.start {\n  border-color: color-mix(in oklab, var(--ok) 32%, var(--line));"), true);
equal(appCss.includes(".ccr-address-switch-btn.active {\n  border-color: var(--control-border-hover);"), true);
equal(appCss.includes(".ccr-env-detail-actions {\n  display: flex;"), true);
equal(appCss.includes(".ccr-gateway-page-tabs"), false);
equal(appCss.includes(".ccr-gateway-page-tab"), false);
equal(appCss.includes(".ccr-main-env {\n  height: auto;\n  min-height: 0;\n  max-height: 100vh;\n  overflow: hidden;"), true);
equal(appCss.includes(".ccr-main-env .ccr-env-results {\n  min-height: 0;\n  overflow: hidden;"), true);
equal(appCss.includes(".ccr-env-app-tabs {\n  padding: 7px;\n  flex: none;"), true);
equal(appCss.includes(".ccr-env-app-tab {\n  width: 38px;\n  height: 38px;"), true);
equal(appCss.includes(".ccr-env-app-tab .ccr-target-logo-frame {\n  flex: 0 0 24px;\n  width: 24px;\n  height: 24px;"), true);
equal(appCss.includes(".ccr-env-detail-card {\n  min-height: 0;\n  max-height: calc(100vh - 188px);\n  display: flex;"), true);
equal(appCss.includes(".ccr-env-detail-card .ccr-env-card-body {\n  flex: 0 1 auto;\n  min-height: 0;\n  gap: 14px;\n  align-content: start;\n  overflow-y: auto;"), true);
equal(appCss.includes(".ccr-env-empty-state {\n  display: grid;\n  gap: 12px;\n  align-content: start;"), true);
equal(appCss.includes("--button-warning-border"), true);
equal(appCss.includes(".ccr-env-install-action,\n.ccr-env-upgrade-action,\n.ccr-env-uninstall-action {\n  height: 28px !important;"), true);
equal(appCss.includes(".ccr-env-title-line {\n  display: flex;"), true);
equal(appCss.includes(".ccr-env-title-status {\n  flex: none;"), true);
equal(appCss.includes(".ccr-env-install-static-action"), false);
equal(appCss.includes(".ccr-env-install-action,\n.ccr-env-upgrade-action {\n  border-color: var(--line-2) !important;"), false);
equal(appCss.includes(".ccr-env-install-action {\n  border-color: color-mix(in oklab, var(--ok) 32%, var(--line)) !important;"), true);
equal(appCss.includes(".ccr-env-install-action:hover {\n  border-color: color-mix(in oklab, var(--ok) 42%, var(--line)) !important;"), true);
equal(appCss.includes(".ccr-env-install-action:hover,\n.ccr-env-upgrade-action:hover {\n  border-color: var(--control-border-hover) !important;"), false);
equal(appCss.includes(".ccr-env-install-action svg,\n.ccr-env-upgrade-action svg,\n.ccr-env-uninstall-action svg {\n  width: 12px !important;"), true);
equal(appCss.includes(".ccr-env-delete-action {\n  height: 26px !important;"), true);
equal(appCss.includes("height: 100vh"), true);
equal(appCss.includes("border-left: 0"), false);
equal(appCss.includes("border-radius: 0 15px 15px 0"), false);
equal(appCss.includes("border-right: 1px solid var(--line)"), false);
equal(sidebarFooterCss.includes("border-top"), false);
equal(appCss.includes("grid-template-columns: clamp(var(--sidebar-min-width), var(--sidebar-width), var(--sidebar-max-width)) 1fr"), true);
equal(tauriCapability.permissions.includes("core:window:allow-start-dragging"), true);
equal(tauriCapability.permissions.includes("core:window:allow-close"), false);
equal(tauriCapability.permissions.includes("core:window:allow-minimize"), false);
equal(tauriCapability.permissions.includes("core:window:allow-set-background-color"), true);
equal(tauriCapability.permissions.includes("core:window:allow-toggle-maximize"), false);
equal(tauriCapability.permissions.includes("core:webview:allow-set-webview-background-color"), true);
