import type { TargetMeta } from "./appTypes.ts";
import { isProxyTarget, type ProxyTargetKey } from "./proxyTargets.ts";

export const claudeDesktopConfigPathLabel = "macOS: ~/Library/Application Support/Claude-3p/configLibrary · Windows: %APPDATA%\\Claude-3p\\configLibrary";

export const targetOptions: TargetMeta[] = [
  {
    key: "codex",
    title: "Codex",
    summary: "Codex CLI/Desktop 的 provider 与本地网关",
    description: "维护 Codex 官方账号登录态、三方 provider 和本地兼容网关。",
    configFileLabel: "Codex 配置文件",
    configFilePath: "~/.codex/config.toml + ~/.codex/auth.json",
    logo: "/target-icons/codex.svg",
    badge: "多端",
  },
  {
    key: "claude_cli",
    title: "Claude Code",
    summary: "命令行配置写回 ~/.claude/settings.json",
    description: "适合为 Claude Code 维护独立的厂商运行参数、Base URL 与模型映射。",
    configFileLabel: "Claude Code 配置文件",
    configFilePath: "~/.claude/settings.json",
    logo: "/target-icons/claude-code.svg",
    badge: "命令行",
  },
  {
    key: "claude_desktop",
    title: "Claude Desktop",
    summary: "桌面端配置写回 Claude-3p/configLibrary",
    description: "维护 Claude Desktop 可切换的厂商配置，并指定当前 appliedId。",
    configFileLabel: "Claude 桌面端配置库",
    configFilePath: claudeDesktopConfigPathLabel,
    logo: "/target-icons/claude.svg",
    badge: "桌面端",
  },
  {
    key: "hermes",
    title: "Hermes Agent",
    summary: "Hermes Agent CLI/Desktop 厂商配置管理",
    description: "维护 Hermes Agent CLI 与 Desktop 共享的厂商配置，并写入 ~/.hermes/config.yaml。",
    configFileLabel: "Hermes 共享配置文件",
    configFilePath: "~/.hermes/config.yaml",
    logo: "/target-icons/hermes.png",
    badge: "多端",
  },
  {
    key: "opencode",
    title: "OpenCode",
    summary: "OpenCode 厂商配置管理",
    description: "维护 OpenCode 的 OpenAI-compatible 厂商配置，并写入 opencode.json。",
    configFileLabel: "OpenCode 配置文件",
    configFilePath: "~/.config/opencode/opencode.json",
    logo: "/target-icons/opencode.png",
    badge: "配置",
  },
  {
    key: "oh_my_opencode",
    title: "Oh My OpenAgent",
    summary: "OpenCode 插件增强配置",
    description: "维护 Oh My OpenAgent 的 agent 与任务分类模型路由；依赖 OpenCode，启动入口仍是 opencode，并复用 OpenCode provider 配置。",
    configFileLabel: "Oh My OpenAgent 路由配置",
    configFilePath: "~/.config/opencode/oh-my-openagent.json",
    logo: "/target-icons/oh-my-openagent.svg",
    badge: "增强",
  },
  {
    key: "openclaw",
    title: "OpenClaw",
    summary: "OpenClaw 厂商配置管理",
    description: "维护 OpenClaw 的厂商配置，并写入 openclaw.json。",
    configFileLabel: "OpenClaw 配置文件",
    configFilePath: "~/.openclaw/openclaw.json",
    logo: "/target-icons/openclaw.svg",
    badge: "配置",
  },
  {
    key: "pi",
    title: "Pi",
    summary: "Pi Coding Agent 厂商配置管理",
    description: "维护 Pi Coding Agent 的 custom provider、默认 provider 与默认模型。",
    configFileLabel: "Pi 配置文件",
    configFilePath: "~/.pi/agent/models.json + ~/.pi/agent/settings.json",
    logo: "/target-icons/pi.svg",
    badge: "命令行",
  },
  {
    key: "oh_my_pi",
    title: "Oh My Pi",
    summary: "独立增强版 Pi CLI 配置管理",
    description: "维护独立安装的 Oh My Pi provider 与 agent/category 模型路由；启动入口是 omp，不依赖 Pi 命令。",
    configFileLabel: "Oh My Pi 配置文件",
    configFilePath: "~/.omp/agent/models.yml",
    logo: "/target-icons/oh-my-pi.svg",
    badge: "增强",
  },
  {
    key: "antigravity",
    title: "Antigravity",
    summary: "Antigravity 厂商配置管理",
    description: "维护 Antigravity 的厂商配置。当前先管理 Switch++ 内部配置列表，客户端写入契约等待官方稳定后再接入。",
    configFileLabel: "Antigravity 配置文件",
    configFilePath: "~/.gemini/antigravity-cli/settings.json + ~/.gemini/antigravity/mcp_config.json",
    logo: "/target-icons/antigravity.png",
    badge: "配置",
    disabled: true,
    disabledReason: "Antigravity 官方暂未公开稳定的第三方模型配置写入字段，暂不可用。",
  },
];

export const gatewayProxyTargetOptions = targetOptions.filter(
  (option): option is TargetMeta & { key: ProxyTargetKey } => isProxyTarget(option.key),
);
export const visibleTargetOptions = targetOptions.filter((option) => option.key !== "antigravity");
